# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\helper_ui\loeschen.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        Dialog.resize(400, 344)
        Dialog.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        Dialog.setModal(True)
        self.Btn_OK_Abbruch = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.Btn_OK_Abbruch.setGeometry(QtCore.QRect(190, 260, 191, 46))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Btn_OK_Abbruch.setFont(font)
        self.Btn_OK_Abbruch.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border-radius: 4px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_OK_Abbruch.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Btn_OK_Abbruch.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.Btn_OK_Abbruch.setObjectName("Btn_OK_Abbruch")
        self.lbl_Loeschen = QtWidgets.QLabel(parent=Dialog)
        self.lbl_Loeschen.setGeometry(QtCore.QRect(-2, 5, 401, 251))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.lbl_Loeschen.sizePolicy().hasHeightForWidth())
        self.lbl_Loeschen.setSizePolicy(sizePolicy)
        self.lbl_Loeschen.setText("")
        self.lbl_Loeschen.setPixmap(QtGui.QPixmap("e:\\Python\\Python_WORK\\Datei_Info_Creator\\gui\\uic_imports\\helper_ui\\../grafics/loeschen.jpg"))
        self.lbl_Loeschen.setScaledContents(True)
        self.lbl_Loeschen.setObjectName("lbl_Loeschen")
        self.lbl_DELDatei = QtWidgets.QLabel(parent=Dialog)
        self.lbl_DELDatei.setGeometry(QtCore.QRect(10, 310, 381, 20))
        self.lbl_DELDatei.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_DELDatei.setText("")
        self.lbl_DELDatei.setObjectName("lbl_DELDatei")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(10, 280, 111, 16))
        self.label_2.setObjectName("label_2")
        self.lbl_Loeschen.raise_()
        self.Btn_OK_Abbruch.raise_()
        self.lbl_DELDatei.raise_()
        self.label_2.raise_()

        self.retranslateUi(Dialog)
        self.Btn_OK_Abbruch.accepted.connect(Dialog.accept) # type: ignore
        self.Btn_OK_Abbruch.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Soll die Datei wirklich gelöscht werden ?"))
        self.label_2.setText(_translate("Dialog", "zu löschenede Datei:"))
