# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\helper_ui\msg_box_timer.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dlg_Timer(object):
    def setupUi(self, Dlg_Timer):
        Dlg_Timer.setObjectName("Dlg_Timer")
        Dlg_Timer.resize(417, 392)
        Dlg_Timer.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(Dlg_Timer)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setContentsMargins(0, 25, -1, 25)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_timer = QtWidgets.QLabel(parent=Dlg_Timer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.MinimumExpanding, QtWidgets.QSizePolicy.Policy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(150)
        sizePolicy.setVerticalStretch(150)
        sizePolicy.setHeightForWidth(self.lbl_timer.sizePolicy().hasHeightForWidth())
        self.lbl_timer.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(90)
        self.lbl_timer.setFont(font)
        self.lbl_timer.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lbl_timer.setObjectName("lbl_timer")
        self.verticalLayout.addWidget(self.lbl_timer)
        self.lbl_message = QtWidgets.QLabel(parent=Dlg_Timer)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_message.sizePolicy().hasHeightForWidth())
        self.lbl_message.setSizePolicy(sizePolicy)
        self.lbl_message.setMinimumSize(QtCore.QSize(200, 50))
        self.lbl_message.setBaseSize(QtCore.QSize(0, 100))
        self.lbl_message.setText("")
        self.lbl_message.setAlignment(QtCore.Qt.AlignmentFlag.AlignBottom|QtCore.Qt.AlignmentFlag.AlignHCenter)
        self.lbl_message.setObjectName("lbl_message")
        self.verticalLayout.addWidget(self.lbl_message)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(Dlg_Timer)
        QtCore.QMetaObject.connectSlotsByName(Dlg_Timer)

    def retranslateUi(self, Dlg_Timer):
        _translate = QtCore.QCoreApplication.translate
        Dlg_Timer.setWindowTitle(_translate("Dlg_Timer", "Info Box mit Timer"))
        self.lbl_timer.setText(_translate("Dlg_Timer", "5"))
