# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\helper_ui\settings_for_iafd_performer.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_Einstellungen(object):
    def setupUi(self, dlg_Einstellungen):
        dlg_Einstellungen.setObjectName("dlg_Einstellungen")
        dlg_Einstellungen.resize(262, 84)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlg_Einstellungen.sizePolicy().hasHeightForWidth())
        dlg_Einstellungen.setSizePolicy(sizePolicy)
        dlg_Einstellungen.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        dlg_Einstellungen.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dlg_Einstellungen)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkBox_get_autom_iafd = QtWidgets.QCheckBox(parent=dlg_Einstellungen)
        self.chkBox_get_autom_iafd.setEnabled(True)
        self.chkBox_get_autom_iafd.setMinimumSize(QtCore.QSize(0, 30))
        self.chkBox_get_autom_iafd.setMaximumSize(QtCore.QSize(16777215, 30))
        self.chkBox_get_autom_iafd.setTristate(False)
        self.chkBox_get_autom_iafd.setObjectName("chkBox_get_autom_iafd")
        self.verticalLayout.addWidget(self.chkBox_get_autom_iafd)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Btn_OK = QtWidgets.QPushButton(parent=dlg_Einstellungen)
        self.Btn_OK.setMinimumSize(QtCore.QSize(50, 0))
        self.Btn_OK.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_OK.setObjectName("Btn_OK")
        self.horizontalLayout.addWidget(self.Btn_OK)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(dlg_Einstellungen)
        QtCore.QMetaObject.connectSlotsByName(dlg_Einstellungen)

    def retranslateUi(self, dlg_Einstellungen):
        _translate = QtCore.QCoreApplication.translate
        dlg_Einstellungen.setWindowTitle(_translate("dlg_Einstellungen", "Einstellungen"))
        self.chkBox_get_autom_iafd.setToolTip(_translate("dlg_Einstellungen", "Automatisch Link erstellen und webscrapen"))
        self.chkBox_get_autom_iafd.setText(_translate("dlg_Einstellungen", "Automatisch IAFD Link erstelen und einsetzen"))
        self.Btn_OK.setText(_translate("dlg_Einstellungen", "OK"))
