# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\helper_ui\transfer.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(706, 554)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Dialog.setModal(False)
        self.prgBar_Transfer = QtWidgets.QProgressBar(parent=Dialog)
        self.prgBar_Transfer.setGeometry(QtCore.QRect(30, 400, 664, 25))
        self.prgBar_Transfer.setProperty("value", 0)
        self.prgBar_Transfer.setObjectName("prgBar_Transfer")
        self.lbl_move_file = QtWidgets.QLabel(parent=Dialog)
        self.lbl_move_file.setGeometry(QtCore.QRect(30, 20, 651, 16))
        self.lbl_move_file.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_move_file.setText("")
        self.lbl_move_file.setObjectName("lbl_move_file")
        self.lbl_speed = QtWidgets.QLabel(parent=Dialog)
        self.lbl_speed.setGeometry(QtCore.QRect(30, 450, 641, 41))
        self.lbl_speed.setText("")
        self.lbl_speed.setObjectName("lbl_speed")
        self.btn_Stop = QtWidgets.QPushButton(parent=Dialog)
        self.btn_Stop.setGeometry(QtCore.QRect(100, 500, 530, 25))
        self.btn_Stop.setObjectName("btn_Stop")
        self.btn_OK_transfer = QtWidgets.QPushButton(parent=Dialog)
        self.btn_OK_transfer.setGeometry(QtCore.QRect(100, 500, 530, 25))
        self.btn_OK_transfer.setObjectName("btn_OK_transfer")
        self.btn_OK_exif = QtWidgets.QPushButton(parent=Dialog)
        self.btn_OK_exif.setGeometry(QtCore.QRect(100, 500, 530, 25))
        self.btn_OK_exif.setObjectName("btn_OK_exif")
        self.grpBox_dest = QtWidgets.QGroupBox(parent=Dialog)
        self.grpBox_dest.setGeometry(QtCore.QRect(10, 340, 680, 50))
        self.grpBox_dest.setObjectName("grpBox_dest")
        self.lbl_Dest_Folder = QtWidgets.QLabel(parent=self.grpBox_dest)
        self.lbl_Dest_Folder.setGeometry(QtCore.QRect(20, 20, 651, 20))
        self.lbl_Dest_Folder.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_Dest_Folder.setText("")
        self.lbl_Dest_Folder.setObjectName("lbl_Dest_Folder")
        self.grpBox_source = QtWidgets.QGroupBox(parent=Dialog)
        self.grpBox_source.setGeometry(QtCore.QRect(10, 286, 680, 50))
        self.grpBox_source.setObjectName("grpBox_source")
        self.lbl_Source_Folder = QtWidgets.QLabel(parent=self.grpBox_source)
        self.lbl_Source_Folder.setGeometry(QtCore.QRect(20, 20, 654, 20))
        self.lbl_Source_Folder.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_Source_Folder.setText("")
        self.lbl_Source_Folder.setObjectName("lbl_Source_Folder")
        self.label_gif_transfer = QtWidgets.QLabel(parent=Dialog)
        self.label_gif_transfer.setGeometry(QtCore.QRect(20, 40, 661, 241))
        self.label_gif_transfer.setText("")
        self.label_gif_transfer.setScaledContents(True)
        self.label_gif_transfer.setObjectName("label_gif_transfer")
        self.btn_Stop.raise_()
        self.btn_OK_exif.raise_()
        self.grpBox_source.raise_()
        self.grpBox_dest.raise_()
        self.btn_OK_transfer.raise_()
        self.prgBar_Transfer.raise_()
        self.lbl_move_file.raise_()
        self.lbl_speed.raise_()
        self.label_gif_transfer.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Datei Transfer"))
        self.btn_Stop.setText(_translate("Dialog", "STOP"))
        self.btn_OK_transfer.setText(_translate("Dialog", "Transfer OK"))
        self.btn_OK_exif.setText(_translate("Dialog", "OK"))
        self.grpBox_dest.setTitle(_translate("Dialog", "     Ziel-Ordner:"))
        self.grpBox_source.setTitle(_translate("Dialog", "     Quelle-Ordner:"))
