# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_gui\dialog_scrape_actor_infos.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(943, 426)
        Dialog.setModal(True)
        self.tabWidget = QtWidgets.QTabWidget(parent=Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(20, 10, 911, 371))
        self.tabWidget.setObjectName("tabWidget")
        self.actor_info = QtWidgets.QWidget()
        self.actor_info.setObjectName("actor_info")
        self.layoutWidget_9 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_9.setGeometry(QtCore.QRect(490, 110, 190, 22))
        self.layoutWidget_9.setObjectName("layoutWidget_9")
        self.HLayout_birthday = QtWidgets.QHBoxLayout(self.layoutWidget_9)
        self.HLayout_birthday.setContentsMargins(0, 0, 0, 0)
        self.HLayout_birthday.setObjectName("HLayout_birthday")
        self.lblgeburtstag = QtWidgets.QLabel(parent=self.layoutWidget_9)
        self.lblgeburtstag.setObjectName("lblgeburtstag")
        self.HLayout_birthday.addWidget(self.lblgeburtstag)
        self.lnEdit_performer_birthday = ClickableQLineEdit(parent=self.layoutWidget_9)
        self.lnEdit_performer_birthday.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_birthday.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_birthday.setText("")
        self.lnEdit_performer_birthday.setPlaceholderText("kein Eintrag")
        self.lnEdit_performer_birthday.setObjectName("lnEdit_performer_birthday")
        self.HLayout_birthday.addWidget(self.lnEdit_performer_birthday)
        self.layoutWidget = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 80, 190, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.HLayout_hair_colour = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.HLayout_hair_colour.setContentsMargins(0, 0, 0, 0)
        self.HLayout_hair_colour.setObjectName("HLayout_hair_colour")
        self.lblactor_hair_colour = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lblactor_hair_colour.setObjectName("lblactor_hair_colour")
        self.HLayout_hair_colour.addWidget(self.lblactor_hair_colour)
        self.lnEdit_performer_hair = ClickableQLineEdit(parent=self.layoutWidget)
        self.lnEdit_performer_hair.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_hair.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_hair.setText("")
        self.lnEdit_performer_hair.setPlaceholderText("kein Eintrag")
        self.lnEdit_performer_hair.setObjectName("lnEdit_performer_hair")
        self.HLayout_hair_colour.addWidget(self.lnEdit_performer_hair)
        self.layoutWidget_8 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_8.setGeometry(QtCore.QRect(490, 80, 291, 22))
        self.layoutWidget_8.setObjectName("layoutWidget_8")
        self.HLayout_bithplace = QtWidgets.QHBoxLayout(self.layoutWidget_8)
        self.HLayout_bithplace.setContentsMargins(0, 0, 0, 0)
        self.HLayout_bithplace.setObjectName("HLayout_bithplace")
        self.lblgeburtsort = QtWidgets.QLabel(parent=self.layoutWidget_8)
        self.lblgeburtsort.setObjectName("lblgeburtsort")
        self.HLayout_bithplace.addWidget(self.lblgeburtsort)
        self.lnEdit_performer_birthplace = ClickableQLineEdit(parent=self.layoutWidget_8)
        self.lnEdit_performer_birthplace.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_birthplace.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_birthplace.setText("")
        self.lnEdit_performer_birthplace.setPlaceholderText("kein Eintrag")
        self.lnEdit_performer_birthplace.setObjectName("lnEdit_performer_birthplace")
        self.HLayout_bithplace.addWidget(self.lnEdit_performer_birthplace)
        self.layoutWidget_11 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_11.setGeometry(QtCore.QRect(490, 140, 190, 22))
        self.layoutWidget_11.setObjectName("layoutWidget_11")
        self.HLayout_boobs = QtWidgets.QHBoxLayout(self.layoutWidget_11)
        self.HLayout_boobs.setContentsMargins(0, 0, 0, 0)
        self.HLayout_boobs.setObjectName("HLayout_boobs")
        self.lblboobs = QtWidgets.QLabel(parent=self.layoutWidget_11)
        self.lblboobs.setObjectName("lblboobs")
        self.HLayout_boobs.addWidget(self.lblboobs)
        self.lnEdit_performer_boobs = ClickableQLineEdit(parent=self.layoutWidget_11)
        self.lnEdit_performer_boobs.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_boobs.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_boobs.setInputMask("")
        self.lnEdit_performer_boobs.setText("")
        self.lnEdit_performer_boobs.setPlaceholderText("kein Eintrag")
        self.lnEdit_performer_boobs.setObjectName("lnEdit_performer_boobs")
        self.HLayout_boobs.addWidget(self.lnEdit_performer_boobs)
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_2.setGeometry(QtCore.QRect(701, 141, 107, 22))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.HLayout_height = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.HLayout_height.setContentsMargins(0, 0, 0, 0)
        self.HLayout_height.setObjectName("HLayout_height")
        self.lblperformer_groesse = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.lblperformer_groesse.setMinimumSize(QtCore.QSize(45, 0))
        self.lblperformer_groesse.setMaximumSize(QtCore.QSize(45, 16777215))
        self.lblperformer_groesse.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblperformer_groesse.setObjectName("lblperformer_groesse")
        self.HLayout_height.addWidget(self.lblperformer_groesse)
        self.lnEdit_performer_height = ClickableQLineEdit(parent=self.layoutWidget_2)
        self.lnEdit_performer_height.setMinimumSize(QtCore.QSize(35, 0))
        self.lnEdit_performer_height.setMaximumSize(QtCore.QSize(35, 16777215))
        self.lnEdit_performer_height.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_height.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_height.setText("")
        self.lnEdit_performer_height.setPlaceholderText("0")
        self.lnEdit_performer_height.setObjectName("lnEdit_performer_height")
        self.HLayout_height.addWidget(self.lnEdit_performer_height)
        self.lbl_kg_2 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        self.lbl_kg_2.setObjectName("lbl_kg_2")
        self.HLayout_height.addWidget(self.lbl_kg_2)
        self.layoutWidget_3 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_3.setGeometry(QtCore.QRect(10, 110, 431, 22))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.HLayout_ethnicity = QtWidgets.QHBoxLayout(self.layoutWidget_3)
        self.HLayout_ethnicity.setContentsMargins(0, 0, 0, 0)
        self.HLayout_ethnicity.setObjectName("HLayout_ethnicity")
        self.lblperformer_rasse = QtWidgets.QLabel(parent=self.layoutWidget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblperformer_rasse.sizePolicy().hasHeightForWidth())
        self.lblperformer_rasse.setSizePolicy(sizePolicy)
        self.lblperformer_rasse.setObjectName("lblperformer_rasse")
        self.HLayout_ethnicity.addWidget(self.lblperformer_rasse)
        self.cBox_performer_rasse = QtWidgets.QComboBox(parent=self.layoutWidget_3)
        self.cBox_performer_rasse.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.cBox_performer_rasse.setStyleSheet("background-color: #FFFDD5;")
        self.cBox_performer_rasse.setObjectName("cBox_performer_rasse")
        self.cBox_performer_rasse.addItem("")
        self.cBox_performer_rasse.setItemText(0, "")
        self.cBox_performer_rasse.addItem("")
        self.cBox_performer_rasse.addItem("")
        self.cBox_performer_rasse.addItem("")
        self.cBox_performer_rasse.addItem("")
        self.cBox_performer_rasse.addItem("")
        self.cBox_performer_rasse.addItem("")
        self.cBox_performer_rasse.addItem("")
        self.cBox_performer_rasse.addItem("")
        self.HLayout_ethnicity.addWidget(self.cBox_performer_rasse)
        self.layoutWidget_4 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_4.setGeometry(QtCore.QRect(701, 171, 105, 22))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.HLayout_weight = QtWidgets.QHBoxLayout(self.layoutWidget_4)
        self.HLayout_weight.setContentsMargins(0, 0, 0, 0)
        self.HLayout_weight.setObjectName("HLayout_weight")
        self.lblperformer_gewicht = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.lblperformer_gewicht.setMinimumSize(QtCore.QSize(45, 0))
        self.lblperformer_gewicht.setMaximumSize(QtCore.QSize(45, 16777215))
        self.lblperformer_gewicht.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.lblperformer_gewicht.setObjectName("lblperformer_gewicht")
        self.HLayout_weight.addWidget(self.lblperformer_gewicht)
        self.lnEdit_performer_weight = ClickableQLineEdit(parent=self.layoutWidget_4)
        self.lnEdit_performer_weight.setMinimumSize(QtCore.QSize(35, 0))
        self.lnEdit_performer_weight.setMaximumSize(QtCore.QSize(35, 16777215))
        self.lnEdit_performer_weight.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_weight.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_weight.setText("")
        self.lnEdit_performer_weight.setPlaceholderText("0")
        self.lnEdit_performer_weight.setObjectName("lnEdit_performer_weight")
        self.HLayout_weight.addWidget(self.lnEdit_performer_weight)
        self.lbl_kg = QtWidgets.QLabel(parent=self.layoutWidget_4)
        self.lbl_kg.setObjectName("lbl_kg")
        self.HLayout_weight.addWidget(self.lbl_kg)
        self.layoutWidget_12 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_12.setGeometry(QtCore.QRect(490, 170, 190, 22))
        self.layoutWidget_12.setObjectName("layoutWidget_12")
        self.HLayout_bodytyp = QtWidgets.QHBoxLayout(self.layoutWidget_12)
        self.HLayout_bodytyp.setContentsMargins(0, 0, 0, 0)
        self.HLayout_bodytyp.setObjectName("HLayout_bodytyp")
        self.lblbodytyp = QtWidgets.QLabel(parent=self.layoutWidget_12)
        self.lblbodytyp.setObjectName("lblbodytyp")
        self.HLayout_bodytyp.addWidget(self.lblbodytyp)
        self.lnEdit_performer_meaturements = ClickableQLineEdit(parent=self.layoutWidget_12)
        self.lnEdit_performer_meaturements.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_meaturements.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_meaturements.setText("")
        self.lnEdit_performer_meaturements.setPlaceholderText("kein Eintrag")
        self.lnEdit_performer_meaturements.setObjectName("lnEdit_performer_meaturements")
        self.HLayout_bodytyp.addWidget(self.lnEdit_performer_meaturements)
        self.grpBox_actor_name = QtWidgets.QGroupBox(parent=self.actor_info)
        self.grpBox_actor_name.setGeometry(QtCore.QRect(10, 10, 881, 61))
        self.grpBox_actor_name.setStyleSheet("QGroupBox {\n"
"background-color: rgb(218, 222, 226);\n"
"border: 1px solid grey;border-radius: 5px;}")
        self.grpBox_actor_name.setObjectName("grpBox_actor_name")
        self.lnEdit_performer_name = QtWidgets.QLineEdit(parent=self.grpBox_actor_name)
        self.lnEdit_performer_name.setEnabled(True)
        self.lnEdit_performer_name.setGeometry(QtCore.QRect(450, 20, 411, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lnEdit_performer_name.setFont(font)
        self.lnEdit_performer_name.setStyleSheet("QLabel{background-color:#e3e3e3 }\n"
"")
        self.lnEdit_performer_name.setText("")
        self.lnEdit_performer_name.setFrame(False)
        self.lnEdit_performer_name.setReadOnly(True)
        self.lnEdit_performer_name.setClearButtonEnabled(False)
        self.lnEdit_performer_name.setObjectName("lnEdit_performer_name")
        self.lbl_actor_gender_sign = QtWidgets.QLabel(parent=self.grpBox_actor_name)
        self.lbl_actor_gender_sign.setGeometry(QtCore.QRect(10, 20, 25, 30))
        self.lbl_actor_gender_sign.setText("")
        self.lbl_actor_gender_sign.setPixmap(QtGui.QPixmap(":/Buttons/_buttons/gender/person-weiblich.png"))
        self.lbl_actor_gender_sign.setObjectName("lbl_actor_gender_sign")
        self.lbl_actor_birthday_place = QtWidgets.QLabel(parent=self.grpBox_actor_name)
        self.lbl_actor_birthday_place.setGeometry(QtCore.QRect(50, 30, 381, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_actor_birthday_place.setFont(font)
        self.lbl_actor_birthday_place.setStyleSheet("QLabel{background-color:#e3e3e3 }")
        self.lbl_actor_birthday_place.setText("")
        self.lbl_actor_birthday_place.setObjectName("lbl_actor_birthday_place")
        self.chkBox_send_api = QtWidgets.QCheckBox(parent=self.actor_info)
        self.chkBox_send_api.setGeometry(QtCore.QRect(10, 320, 91, 17))
        self.chkBox_send_api.setObjectName("chkBox_send_api")
        self.layoutWidget_10 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_10.setGeometry(QtCore.QRect(10, 140, 431, 22))
        self.layoutWidget_10.setObjectName("layoutWidget_10")
        self.HLayout_nationality = QtWidgets.QHBoxLayout(self.layoutWidget_10)
        self.HLayout_nationality.setContentsMargins(0, 0, 0, 0)
        self.HLayout_nationality.setObjectName("HLayout_nationality")
        self.lblnationality = QtWidgets.QLabel(parent=self.layoutWidget_10)
        self.lblnationality.setObjectName("lblnationality")
        self.HLayout_nationality.addWidget(self.lblnationality)
        self.lnEdit_performer_nationality = ClickableQLineEdit(parent=self.layoutWidget_10)
        self.lnEdit_performer_nationality.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_nationality.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_nationality.setText("")
        self.lnEdit_performer_nationality.setPlaceholderText("kein Eintrag")
        self.lnEdit_performer_nationality.setObjectName("lnEdit_performer_nationality")
        self.HLayout_nationality.addWidget(self.lnEdit_performer_nationality)
        self.gBox_tattoo = QtWidgets.QGroupBox(parent=self.actor_info)
        self.gBox_tattoo.setGeometry(QtCore.QRect(459, 200, 431, 81))
        self.gBox_tattoo.setObjectName("gBox_tattoo")
        self.txtEdit_performer_tattoo = ClickableQTextEdit(parent=self.gBox_tattoo)
        self.txtEdit_performer_tattoo.setGeometry(QtCore.QRect(0, 20, 430, 60))
        self.txtEdit_performer_tattoo.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.txtEdit_performer_tattoo.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QToolTip {min-width: 350px;}")
        self.txtEdit_performer_tattoo.setAcceptRichText(False)
        self.txtEdit_performer_tattoo.setObjectName("txtEdit_performer_tattoo")
        self.gBox_piercing = QtWidgets.QGroupBox(parent=self.actor_info)
        self.gBox_piercing.setGeometry(QtCore.QRect(20, 200, 431, 81))
        self.gBox_piercing.setObjectName("gBox_piercing")
        self.txtEdit_performer_piercing = ClickableQTextEdit(parent=self.gBox_piercing)
        self.txtEdit_performer_piercing.setGeometry(QtCore.QRect(0, 20, 430, 60))
        self.txtEdit_performer_piercing.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.ActionsContextMenu)
        self.txtEdit_performer_piercing.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QToolTip {min-width: 350px;}")
        self.txtEdit_performer_piercing.setAcceptRichText(False)
        self.txtEdit_performer_piercing.setObjectName("txtEdit_performer_piercing")
        self.layoutWidget_14 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_14.setGeometry(QtCore.QRect(20, 290, 871, 22))
        self.layoutWidget_14.setObjectName("layoutWidget_14")
        self.HLayout_nationality_2 = QtWidgets.QHBoxLayout(self.layoutWidget_14)
        self.HLayout_nationality_2.setContentsMargins(0, 0, 0, 0)
        self.HLayout_nationality_2.setObjectName("HLayout_nationality_2")
        self.lblnationality_2 = QtWidgets.QLabel(parent=self.layoutWidget_14)
        self.lblnationality_2.setObjectName("lblnationality_2")
        self.HLayout_nationality_2.addWidget(self.lblnationality_2)
        self.lnEdit_performer_aliases = QtWidgets.QLineEdit(parent=self.layoutWidget_14)
        self.lnEdit_performer_aliases.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_aliases.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_aliases.setText("")
        self.lnEdit_performer_aliases.setPlaceholderText("kein Eintrag")
        self.lnEdit_performer_aliases.setObjectName("lnEdit_performer_aliases")
        self.HLayout_nationality_2.addWidget(self.lnEdit_performer_aliases)
        self.layoutWidget_13 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_13.setGeometry(QtCore.QRect(10, 170, 431, 22))
        self.layoutWidget_13.setObjectName("layoutWidget_13")
        self.HLayout_nationality_3 = QtWidgets.QHBoxLayout(self.layoutWidget_13)
        self.HLayout_nationality_3.setContentsMargins(0, 0, 0, 0)
        self.HLayout_nationality_3.setObjectName("HLayout_nationality_3")
        self.lbluuid = QtWidgets.QLabel(parent=self.layoutWidget_13)
        self.lbluuid.setObjectName("lbluuid")
        self.HLayout_nationality_3.addWidget(self.lbluuid)
        self.lnEdit_performer_uuid = ClickableQLineEdit(parent=self.layoutWidget_13)
        self.lnEdit_performer_uuid.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_uuid.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_uuid.setText("")
        self.lnEdit_performer_uuid.setReadOnly(False)
        self.lnEdit_performer_uuid.setPlaceholderText("kein Eintrag")
        self.lnEdit_performer_uuid.setObjectName("lnEdit_performer_uuid")
        self.HLayout_nationality_3.addWidget(self.lnEdit_performer_uuid)
        self.layoutWidget_5 = QtWidgets.QWidget(parent=self.actor_info)
        self.layoutWidget_5.setGeometry(QtCore.QRect(250, 80, 190, 22))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.HLayout_eye_colour = QtWidgets.QHBoxLayout(self.layoutWidget_5)
        self.HLayout_eye_colour.setContentsMargins(0, 0, 0, 0)
        self.HLayout_eye_colour.setObjectName("HLayout_eye_colour")
        self.lblperformer_augen = QtWidgets.QLabel(parent=self.layoutWidget_5)
        self.lblperformer_augen.setObjectName("lblperformer_augen")
        self.HLayout_eye_colour.addWidget(self.lblperformer_augen)
        self.lnEdit_performer_eye = ClickableQLineEdit(parent=self.layoutWidget_5)
        self.lnEdit_performer_eye.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.lnEdit_performer_eye.setStyleSheet("QLineEdit,QTextEdit { \n"
"background-color: #FFFDD5;}\n"
"QLineEdit:hover,QTextEdit:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLineEdit:focus,QTextEdit:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QLineEdit::placeholderText { \n"
"color: rgb(213, 213, 213);}\n"
"\n"
"\n"
"\n"
"\n"
"")
        self.lnEdit_performer_eye.setText("")
        self.lnEdit_performer_eye.setPlaceholderText("kein Eintrag")
        self.lnEdit_performer_eye.setObjectName("lnEdit_performer_eye")
        self.HLayout_eye_colour.addWidget(self.lnEdit_performer_eye)
        self.lbl_status_message = QtWidgets.QLabel(parent=self.actor_info)
        self.lbl_status_message.setGeometry(QtCore.QRect(120, 324, 770, 16))
        self.lbl_status_message.setStyleSheet("QLabel{background-color:#e3e3e3 }")
        self.lbl_status_message.setText("")
        self.lbl_status_message.setObjectName("lbl_status_message")
        self.tabWidget.addTab(self.actor_info, "")
        self.actor_images = QtWidgets.QWidget()
        self.actor_images.setObjectName("actor_images")
        self.scrollArea_actor_images = QtWidgets.QScrollArea(parent=self.actor_images)
        self.scrollArea_actor_images.setGeometry(QtCore.QRect(13, 40, 880, 300))
        self.scrollArea_actor_images.setWidgetResizable(True)
        self.scrollArea_actor_images.setObjectName("scrollArea_actor_images")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 878, 298))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea_actor_images.setWidget(self.scrollAreaWidgetContents)
        self.lbl_image_counter = QtWidgets.QLabel(parent=self.actor_images)
        self.lbl_image_counter.setGeometry(QtCore.QRect(0, 10, 240, 25))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(9)
        self.lbl_image_counter.setFont(font)
        self.lbl_image_counter.setStyleSheet("QLabel {\n"
"background-color: #4e4e4e;\n"
"color: #fffffa;}")
        self.lbl_image_counter.setText("")
        self.lbl_image_counter.setObjectName("lbl_image_counter")
        self.lbl_image_max = QtWidgets.QLabel(parent=self.actor_images)
        self.lbl_image_max.setGeometry(QtCore.QRect(260, 13, 231, 20))
        self.lbl_image_max.setStyleSheet("background-color: rgb(255, 250, 211)")
        self.lbl_image_max.setObjectName("lbl_image_max")
        self.tabWidget.addTab(self.actor_images, "")
        self.page_media_links = QtWidgets.QWidget()
        self.page_media_links.setObjectName("page_media_links")
        self.tblWdg_actor_medialinks = QtWidgets.QTableWidget(parent=self.page_media_links)
        self.tblWdg_actor_medialinks.setGeometry(QtCore.QRect(20, 10, 870, 331))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(8)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferAntialias)
        self.tblWdg_actor_medialinks.setFont(font)
        self.tblWdg_actor_medialinks.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.tblWdg_actor_medialinks.setStyleSheet("background-color: rgb(255, 250, 211)\n"
"")
        self.tblWdg_actor_medialinks.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblWdg_actor_medialinks.setColumnCount(5)
        self.tblWdg_actor_medialinks.setObjectName("tblWdg_actor_medialinks")
        self.tblWdg_actor_medialinks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tblWdg_actor_medialinks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWdg_actor_medialinks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWdg_actor_medialinks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWdg_actor_medialinks.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tblWdg_actor_medialinks.setHorizontalHeaderItem(4, item)
        self.tblWdg_actor_medialinks.horizontalHeader().setVisible(False)
        self.tblWdg_actor_medialinks.horizontalHeader().setCascadingSectionResizes(False)
        self.tblWdg_actor_medialinks.horizontalHeader().setHighlightSections(False)
        self.tblWdg_actor_medialinks.horizontalHeader().setSortIndicatorShown(True)
        self.tblWdg_actor_medialinks.verticalHeader().setVisible(False)
        self.tblWdg_actor_medialinks.verticalHeader().setDefaultSectionSize(20)
        self.tblWdg_actor_medialinks.verticalHeader().setHighlightSections(False)
        self.tblWdg_actor_medialinks.verticalHeader().setMinimumSectionSize(16)
        self.tblWdg_actor_medialinks.verticalHeader().setSortIndicatorShown(True)
        self.tblWdg_actor_medialinks.verticalHeader().setStretchLastSection(False)
        self.tabWidget.addTab(self.page_media_links, "")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.tblWgd_arctor_links = QtWidgets.QTableWidget(parent=self.tab)
        self.tblWgd_arctor_links.setGeometry(QtCore.QRect(8, 10, 890, 331))
        self.tblWgd_arctor_links.setStyleSheet("background-color: rgb(255, 250, 211)")
        self.tblWgd_arctor_links.setObjectName("tblWgd_arctor_links")
        self.tblWgd_arctor_links.setColumnCount(0)
        self.tblWgd_arctor_links.setRowCount(0)
        self.tabWidget.addTab(self.tab, "")
        self.search_actor = QtWidgets.QWidget()
        self.search_actor.setObjectName("search_actor")
        self.grpBox_actor_search_name = QtWidgets.QGroupBox(parent=self.search_actor)
        self.grpBox_actor_search_name.setGeometry(QtCore.QRect(10, 10, 881, 41))
        self.grpBox_actor_search_name.setStyleSheet("QGroupBox {\n"
"background-color: rgb(218, 222, 226);\n"
"border: 1px solid grey;border-radius: 5px;}")
        self.grpBox_actor_search_name.setObjectName("grpBox_actor_search_name")
        self.lnEdit_performer_search_name = QtWidgets.QLineEdit(parent=self.grpBox_actor_search_name)
        self.lnEdit_performer_search_name.setEnabled(True)
        self.lnEdit_performer_search_name.setGeometry(QtCore.QRect(450, 10, 411, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lnEdit_performer_search_name.setFont(font)
        self.lnEdit_performer_search_name.setStyleSheet("QLabel{background-color:#e3e3e3 }\n"
"")
        self.lnEdit_performer_search_name.setText("")
        self.lnEdit_performer_search_name.setFrame(False)
        self.lnEdit_performer_search_name.setReadOnly(False)
        self.lnEdit_performer_search_name.setClearButtonEnabled(False)
        self.lnEdit_performer_search_name.setObjectName("lnEdit_performer_search_name")
        self.lbl_search_counter = QtWidgets.QLabel(parent=self.grpBox_actor_search_name)
        self.lbl_search_counter.setGeometry(QtCore.QRect(10, 20, 181, 16))
        self.lbl_search_counter.setStyleSheet("QLabel{background-color:#e3e3e3 }")
        self.lbl_search_counter.setText("")
        self.lbl_search_counter.setObjectName("lbl_search_counter")
        self.tblWdg_search_result_actors = QtWidgets.QTableWidget(parent=self.search_actor)
        self.tblWdg_search_result_actors.setGeometry(QtCore.QRect(10, 60, 420, 280))
        self.tblWdg_search_result_actors.setStyleSheet("background-color: rgb(255, 250, 211)")
        self.tblWdg_search_result_actors.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tblWdg_search_result_actors.setWordWrap(False)
        self.tblWdg_search_result_actors.setObjectName("tblWdg_search_result_actors")
        self.tblWdg_search_result_actors.setColumnCount(0)
        self.tblWdg_search_result_actors.setRowCount(0)
        self.tblWdg_search_result_actors.horizontalHeader().setDefaultSectionSize(205)
        self.tabWidget.addTab(self.search_actor, "")
        self.Btn_accept = QtWidgets.QPushButton(parent=Dialog)
        self.Btn_accept.setGeometry(QtCore.QRect(850, 390, 75, 23))
        self.Btn_accept.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_accept.setObjectName("Btn_accept")
        self.Btn_upload_datas = QtWidgets.QPushButton(parent=Dialog)
        self.Btn_upload_datas.setGeometry(QtCore.QRect(20, 390, 75, 23))
        self.Btn_upload_datas.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_upload_datas.setObjectName("Btn_upload_datas")
        self.Btn_set_DB_data_in_dialog = QtWidgets.QPushButton(parent=Dialog)
        self.Btn_set_DB_data_in_dialog.setGeometry(QtCore.QRect(100, 390, 111, 23))
        self.Btn_set_DB_data_in_dialog.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_set_DB_data_in_dialog.setObjectName("Btn_set_DB_data_in_dialog")
        self.lbl_loading_progress = QtWidgets.QLabel(parent=Dialog)
        self.lbl_loading_progress.setGeometry(QtCore.QRect(349, 390, 491, 30))
        self.lbl_loading_progress.setText("")
        self.lbl_loading_progress.setObjectName("lbl_loading_progress")
        self.Btn_get_DB_data_in_dialog = QtWidgets.QPushButton(parent=Dialog)
        self.Btn_get_DB_data_in_dialog.setGeometry(QtCore.QRect(216, 390, 110, 23))
        self.Btn_get_DB_data_in_dialog.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_get_DB_data_in_dialog.setObjectName("Btn_get_DB_data_in_dialog")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.lblgeburtstag.setText(_translate("Dialog", "Geburtstag:"))
        self.lblactor_hair_colour.setText(_translate("Dialog", "Haarfarbe"))
        self.lblgeburtsort.setText(_translate("Dialog", "Geburtsort:"))
        self.lblboobs.setText(_translate("Dialog", "Boobs:"))
        self.lblperformer_groesse.setText(_translate("Dialog", "Größe:"))
        self.lnEdit_performer_height.setInputMask(_translate("Dialog", "999"))
        self.lbl_kg_2.setText(_translate("Dialog", "cm"))
        self.lblperformer_rasse.setText(_translate("Dialog", "Ethnizität:"))
        self.cBox_performer_rasse.setItemText(1, _translate("Dialog", "Asian"))
        self.cBox_performer_rasse.setItemText(2, _translate("Dialog", "Black"))
        self.cBox_performer_rasse.setItemText(3, _translate("Dialog", "Caucasian"))
        self.cBox_performer_rasse.setItemText(4, _translate("Dialog", "Indian"))
        self.cBox_performer_rasse.setItemText(5, _translate("Dialog", "Latin"))
        self.cBox_performer_rasse.setItemText(6, _translate("Dialog", "Middle Eastern"))
        self.cBox_performer_rasse.setItemText(7, _translate("Dialog", "Mixed"))
        self.cBox_performer_rasse.setItemText(8, _translate("Dialog", "Others"))
        self.lblperformer_gewicht.setText(_translate("Dialog", "Gewicht:"))
        self.lnEdit_performer_weight.setInputMask(_translate("Dialog", "999"))
        self.lbl_kg.setText(_translate("Dialog", "kg"))
        self.lblbodytyp.setText(_translate("Dialog", "Maße"))
        self.grpBox_actor_name.setTitle(_translate("Dialog", "Performer-Info für:"))
        self.chkBox_send_api.setText(_translate("Dialog", "Send to API"))
        self.lblnationality.setText(_translate("Dialog", "Nationalität:"))
        self.gBox_tattoo.setTitle(_translate("Dialog", "Tattoo:"))
        self.txtEdit_performer_tattoo.setPlaceholderText(_translate("Dialog", "kein Eintrag"))
        self.gBox_piercing.setTitle(_translate("Dialog", "  Piercing:"))
        self.txtEdit_performer_piercing.setPlaceholderText(_translate("Dialog", "kein Eintrag"))
        self.lblnationality_2.setText(_translate("Dialog", "Alias:"))
        self.lbluuid.setText(_translate("Dialog", "UUiD"))
        self.lblperformer_augen.setText(_translate("Dialog", "Augenfarbe"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actor_info), _translate("Dialog", "Infos"))
        self.lbl_image_max.setText(_translate("Dialog", "Maximale Anzahl Bilder: "))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.actor_images), _translate("Dialog", "Bilder"))
        item = self.tblWdg_actor_medialinks.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "ID"))
        item = self.tblWdg_actor_medialinks.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Status"))
        item = self.tblWdg_actor_medialinks.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Image"))
        item = self.tblWdg_actor_medialinks.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Alias"))
        item = self.tblWdg_actor_medialinks.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Status"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.page_media_links), _translate("Dialog", "Media/Bio  Links"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Dialog", "Site Links"))
        self.grpBox_actor_search_name.setTitle(_translate("Dialog", "Nach Name gesucht:"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.search_actor), _translate("Dialog", "Suche nach Performer"))
        self.Btn_accept.setText(_translate("Dialog", "OK"))
        self.Btn_upload_datas.setText(_translate("Dialog", "Upload"))
        self.Btn_set_DB_data_in_dialog.setText(_translate("Dialog", "Füge DB Daten ein"))
        self.Btn_get_DB_data_in_dialog.setText(_translate("Dialog", "hole DB Daten"))
from gui.custom_widgets.customQLineEdit import ClickableQLineEdit
from gui.custom_widgets.customQTextEdit import ClickableQTextEdit
