# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_gui\dialog_show_last_log_theporndb.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_show_log(object):
    def setupUi(self, dialog_show_log):
        dialog_show_log.setObjectName("dialog_show_log")
        dialog_show_log.setWindowModality(QtCore.Qt.WindowModality.WindowModal)
        dialog_show_log.resize(626, 418)
        dialog_show_log.setModal(False)
        self.gridLayout = QtWidgets.QGridLayout(dialog_show_log)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_log_file = QtWidgets.QLabel(parent=dialog_show_log)
        self.lbl_log_file.setObjectName("lbl_log_file")
        self.verticalLayout.addWidget(self.lbl_log_file)
        self.txtBrw_logfile = QtWidgets.QTextBrowser(parent=dialog_show_log)
        self.txtBrw_logfile.setStyleSheet("background-color: #FFFDD5")
        self.txtBrw_logfile.setObjectName("txtBrw_logfile")
        self.verticalLayout.addWidget(self.txtBrw_logfile)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.Btn_accept = QtWidgets.QPushButton(parent=dialog_show_log)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_accept.sizePolicy().hasHeightForWidth())
        self.Btn_accept.setSizePolicy(sizePolicy)
        self.Btn_accept.setMinimumSize(QtCore.QSize(100, 0))
        self.Btn_accept.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 8pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_accept.setObjectName("Btn_accept")
        self.horizontalLayout.addWidget(self.Btn_accept)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(dialog_show_log)
        QtCore.QMetaObject.connectSlotsByName(dialog_show_log)

    def retranslateUi(self, dialog_show_log):
        _translate = QtCore.QCoreApplication.translate
        dialog_show_log.setWindowTitle(_translate("dialog_show_log", "Anzeige der  letzten Log Datei"))
        self.lbl_log_file.setText(_translate("dialog_show_log", "Log datei:"))
        self.Btn_accept.setText(_translate("dialog_show_log", "OK"))
