# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\_alt\Suchergebnisse.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SuchErgebnisse(object):
    def setupUi(self, SuchErgebnisse):
        SuchErgebnisse.setObjectName("SuchErgebnisse")
        SuchErgebnisse.resize(1182, 576)
        self.Btn_Zurueck = QtWidgets.QPushButton(parent=SuchErgebnisse)
        self.Btn_Zurueck.setGeometry(QtCore.QRect(860, 530, 75, 23))
        self.Btn_Zurueck.setObjectName("Btn_Zurueck")
        self.lbl_Titel = QtWidgets.QLabel(parent=SuchErgebnisse)
        self.lbl_Titel.setEnabled(True)
        self.lbl_Titel.setGeometry(QtCore.QRect(70, 270, 311, 16))
        self.lbl_Titel.setObjectName("lbl_Titel")
        self.lbl_Darsteller = QtWidgets.QLabel(parent=SuchErgebnisse)
        self.lbl_Darsteller.setGeometry(QtCore.QRect(70, 300, 311, 16))
        self.lbl_Darsteller.setObjectName("lbl_Darsteller")
        self.lbl_Link = QtWidgets.QLabel(parent=SuchErgebnisse)
        self.lbl_Link.setGeometry(QtCore.QRect(70, 330, 321, 16))
        self.lbl_Link.setObjectName("lbl_Link")
        self.txt_Link = QtWidgets.QTextBrowser(parent=SuchErgebnisse)
        self.txt_Link.setGeometry(QtCore.QRect(60, 360, 871, 111))
        self.txt_Link.setObjectName("txt_Link")

        self.retranslateUi(SuchErgebnisse)
        QtCore.QMetaObject.connectSlotsByName(SuchErgebnisse)

    def retranslateUi(self, SuchErgebnisse):
        _translate = QtCore.QCoreApplication.translate
        SuchErgebnisse.setWindowTitle(_translate("SuchErgebnisse", "Suchen nach Daten"))
        SuchErgebnisse.setWhatsThis(_translate("SuchErgebnisse", "Ergebnis"))
        self.Btn_Zurueck.setText(_translate("SuchErgebnisse", "Zurück"))
        self.lbl_Titel.setText(_translate("SuchErgebnisse", "Titel"))
        self.lbl_Darsteller.setText(_translate("SuchErgebnisse", "Darsteller"))
        self.lbl_Link.setText(_translate("SuchErgebnisse", "Link"))
