# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_ui\dialog_performer_add_nameslink.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_performer_add_from_link(object):
    def setupUi(self, dialog_performer_add_from_link):
        dialog_performer_add_from_link.setObjectName("dialog_performer_add_from_link")
        dialog_performer_add_from_link.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dialog_performer_add_from_link.resize(502, 170)
        dialog_performer_add_from_link.setWindowTitle("")
        dialog_performer_add_from_link.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dialog_performer_add_from_link)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblpic_link = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lblpic_link.setMinimumSize(QtCore.QSize(25, 25))
        self.lblpic_link.setMaximumSize(QtCore.QSize(25, 25))
        self.lblpic_link.setAutoFillBackground(True)
        self.lblpic_link.setStyleSheet("")
        self.lblpic_link.setText("")
        self.lblpic_link.setPixmap(QtGui.QPixmap(":/labels/_labels/link.png"))
        self.lblpic_link.setScaledContents(False)
        self.lblpic_link.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblpic_link.setObjectName("lblpic_link")
        self.horizontalLayout_2.addWidget(self.lblpic_link)
        self.lbl_link = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_link.setMinimumSize(QtCore.QSize(40, 25))
        self.lbl_link.setMaximumSize(QtCore.QSize(30, 25))
        self.lbl_link.setObjectName("lbl_link")
        self.horizontalLayout_2.addWidget(self.lbl_link)
        self.lnEdit_link = QtWidgets.QLineEdit(parent=dialog_performer_add_from_link)
        self.lnEdit_link.setMinimumSize(QtCore.QSize(390, 25))
        self.lnEdit_link.setMaximumSize(QtCore.QSize(390, 25))
        self.lnEdit_link.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lnEdit_link.setInputMask("")
        self.lnEdit_link.setObjectName("lnEdit_link")
        self.horizontalLayout_2.addWidget(self.lnEdit_link)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblpic_ordner = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lblpic_ordner.setMinimumSize(QtCore.QSize(25, 25))
        self.lblpic_ordner.setMaximumSize(QtCore.QSize(25, 25))
        self.lblpic_ordner.setAutoFillBackground(True)
        self.lblpic_ordner.setStyleSheet("")
        self.lblpic_ordner.setText("")
        self.lblpic_ordner.setPixmap(QtGui.QPixmap(":/labels/_labels/image_ordner.png"))
        self.lblpic_ordner.setScaledContents(True)
        self.lblpic_ordner.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblpic_ordner.setObjectName("lblpic_ordner")
        self.horizontalLayout_3.addWidget(self.lblpic_ordner)
        self.lbl_ordner = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_ordner.setMinimumSize(QtCore.QSize(40, 25))
        self.lbl_ordner.setMaximumSize(QtCore.QSize(30, 25))
        self.lbl_ordner.setObjectName("lbl_ordner")
        self.horizontalLayout_3.addWidget(self.lbl_ordner)
        self.Btn_image_scrape = QtWidgets.QPushButton(parent=dialog_performer_add_from_link)
        self.Btn_image_scrape.setEnabled(False)
        self.Btn_image_scrape.setMinimumSize(QtCore.QSize(120, 25))
        self.Btn_image_scrape.setMaximumSize(QtCore.QSize(120, 25))
        self.Btn_image_scrape.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_image_scrape.setObjectName("Btn_image_scrape")
        self.horizontalLayout_3.addWidget(self.Btn_image_scrape)
        self.Btn_id_merge = QtWidgets.QPushButton(parent=dialog_performer_add_from_link)
        self.Btn_id_merge.setEnabled(False)
        self.Btn_id_merge.setMinimumSize(QtCore.QSize(150, 25))
        self.Btn_id_merge.setMaximumSize(QtCore.QSize(150, 25))
        self.Btn_id_merge.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_id_merge.setObjectName("Btn_id_merge")
        self.horizontalLayout_3.addWidget(self.Btn_id_merge)
        self.Btn_performer_id_merge = QtWidgets.QDialogButtonBox(parent=dialog_performer_add_from_link)
        self.Btn_performer_id_merge.setMinimumSize(QtCore.QSize(100, 25))
        self.Btn_performer_id_merge.setMaximumSize(QtCore.QSize(100, 25))
        self.Btn_performer_id_merge.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_performer_id_merge.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Btn_performer_id_merge.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.Btn_performer_id_merge.setCenterButtons(False)
        self.Btn_performer_id_merge.setObjectName("Btn_performer_id_merge")
        self.horizontalLayout_3.addWidget(self.Btn_performer_id_merge)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblnames_id = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lblnames_id.setMinimumSize(QtCore.QSize(50, 0))
        self.lblnames_id.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lblnames_id.setObjectName("lblnames_id")
        self.horizontalLayout.addWidget(self.lblnames_id)
        self.lbl_names_id_db = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_names_id_db.setMinimumSize(QtCore.QSize(100, 16))
        self.lbl_names_id_db.setMaximumSize(QtCore.QSize(150, 16))
        self.lbl_names_id_db.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_names_id_db.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_names_id_db.setText("")
        self.lbl_names_id_db.setObjectName("lbl_names_id_db")
        self.horizontalLayout.addWidget(self.lbl_names_id_db)
        self.lblartist_id = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lblartist_id.setMinimumSize(QtCore.QSize(50, 0))
        self.lblartist_id.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lblartist_id.setObjectName("lblartist_id")
        self.horizontalLayout.addWidget(self.lblartist_id)
        self.lbl_artist_id_db = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_artist_id_db.setMinimumSize(QtCore.QSize(100, 16))
        self.lbl_artist_id_db.setMaximumSize(QtCore.QSize(160, 16))
        self.lbl_artist_id_db.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_artist_id_db.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_artist_id_db.setText("")
        self.lbl_artist_id_db.setObjectName("lbl_artist_id_db")
        self.horizontalLayout.addWidget(self.lbl_artist_id_db)
        self.lblartist_id_2 = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lblartist_id_2.setMinimumSize(QtCore.QSize(50, 0))
        self.lblartist_id_2.setMaximumSize(QtCore.QSize(50, 16777215))
        self.lblartist_id_2.setObjectName("lblartist_id_2")
        self.horizontalLayout.addWidget(self.lblartist_id_2)
        self.lbl_artist_id2_db = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_artist_id2_db.setMinimumSize(QtCore.QSize(100, 16))
        self.lbl_artist_id2_db.setMaximumSize(QtCore.QSize(160, 16))
        self.lbl_artist_id2_db.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_artist_id2_db.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_artist_id2_db.setText("")
        self.lbl_artist_id2_db.setObjectName("lbl_artist_id2_db")
        self.horizontalLayout.addWidget(self.lbl_artist_id2_db)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.lbl_link_db = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_link_db.setMinimumSize(QtCore.QSize(480, 16))
        self.lbl_link_db.setMaximumSize(QtCore.QSize(480, 16))
        self.lbl_link_db.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_link_db.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_link_db.setText("")
        self.lbl_link_db.setObjectName("lbl_link_db")
        self.verticalLayout.addWidget(self.lbl_link_db)
        self.lbl_ordner_db = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_ordner_db.setMinimumSize(QtCore.QSize(480, 16))
        self.lbl_ordner_db.setMaximumSize(QtCore.QSize(480, 16))
        self.lbl_ordner_db.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_ordner_db.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_ordner_db.setText("")
        self.lbl_ordner_db.setObjectName("lbl_ordner_db")
        self.verticalLayout.addWidget(self.lbl_ordner_db)
        self.lbl_alias_db = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_alias_db.setMinimumSize(QtCore.QSize(480, 16))
        self.lbl_alias_db.setMaximumSize(QtCore.QSize(480, 16))
        self.lbl_alias_db.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_alias_db.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_alias_db.setText("")
        self.lbl_alias_db.setObjectName("lbl_alias_db")
        self.verticalLayout.addWidget(self.lbl_alias_db)
        self.gridLayout.addLayout(self.verticalLayout, 2, 0, 1, 1)

        self.retranslateUi(dialog_performer_add_from_link)
        self.Btn_performer_id_merge.accepted.connect(dialog_performer_add_from_link.accept) # type: ignore
        self.Btn_performer_id_merge.rejected.connect(dialog_performer_add_from_link.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_performer_add_from_link)

    def retranslateUi(self, dialog_performer_add_from_link):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_link.setText(_translate("dialog_performer_add_from_link", "Link:"))
        self.lnEdit_link.setToolTip(_translate("dialog_performer_add_from_link", "<html><head/><body><p>Performer Name eingeben !</p></body></html>"))
        self.lbl_ordner.setText(_translate("dialog_performer_add_from_link", "Image"))
        self.Btn_image_scrape.setText(_translate("dialog_performer_add_from_link", "Image webscrapen"))
        self.Btn_id_merge.setText(_translate("dialog_performer_add_from_link", "Mit ID zusammenfügen"))
        self.lblnames_id.setText(_translate("dialog_performer_add_from_link", "NamesID:"))
        self.lblartist_id.setText(_translate("dialog_performer_add_from_link", "ArtistID 1:"))
        self.lblartist_id_2.setText(_translate("dialog_performer_add_from_link", "+ ArtistID 2:"))
