# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_ui\dialog_datei_auswahl_if_double.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(648, 267)
        Dialog.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.ArrowCursor))
        Dialog.setModal(True)
        self.lbl_move_file = QtWidgets.QLabel(parent=Dialog)
        self.lbl_move_file.setGeometry(QtCore.QRect(30, 20, 591, 16))
        self.lbl_move_file.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_move_file.setText("")
        self.lbl_move_file.setObjectName("lbl_move_file")
        self.rdBtn_SourceDatei = QtWidgets.QRadioButton(parent=Dialog)
        self.rdBtn_SourceDatei.setGeometry(QtCore.QRect(20, 70, 611, 41))
        self.rdBtn_SourceDatei.setText("")
        self.rdBtn_SourceDatei.setObjectName("rdBtn_SourceDatei")
        self.rdBtn_TargetDatei = QtWidgets.QRadioButton(parent=Dialog)
        self.rdBtn_TargetDatei.setGeometry(QtCore.QRect(20, 150, 621, 41))
        self.rdBtn_TargetDatei.setText("")
        self.rdBtn_TargetDatei.setChecked(True)
        self.rdBtn_TargetDatei.setObjectName("rdBtn_TargetDatei")
        self.btn_OK_radioBtn = QtWidgets.QPushButton(parent=Dialog)
        self.btn_OK_radioBtn.setGeometry(QtCore.QRect(60, 220, 531, 23))
        self.btn_OK_radioBtn.setStyleSheet("background-color: rgb(214, 214, 214);")
        self.btn_OK_radioBtn.setObjectName("btn_OK_radioBtn")
        self.rdBtn_SourceDatei.raise_()
        self.rdBtn_TargetDatei.raise_()
        self.lbl_move_file.raise_()
        self.btn_OK_radioBtn.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Datei Auswahl für Datei Transfer"))
        self.btn_OK_radioBtn.setText(_translate("Dialog", "OK"))
