# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_ui\dialog_set_socialmedia_link.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_set_socialmedia_link(object):
    def setupUi(self, dialog_set_socialmedia_link):
        dialog_set_socialmedia_link.setObjectName("dialog_set_socialmedia_link")
        dialog_set_socialmedia_link.resize(400, 73)
        dialog_set_socialmedia_link.setMinimumSize(QtCore.QSize(400, 25))
        dialog_set_socialmedia_link.setMaximumSize(QtCore.QSize(400, 73))
        dialog_set_socialmedia_link.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dialog_set_socialmedia_link)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.lnEdit_socialmedia_link = QtWidgets.QLineEdit(parent=dialog_set_socialmedia_link)
        self.lnEdit_socialmedia_link.setObjectName("lnEdit_socialmedia_link")
        self.verticalLayout.addWidget(self.lnEdit_socialmedia_link)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_socialmedia_icon = QtWidgets.QLabel(parent=dialog_set_socialmedia_link)
        self.lbl_socialmedia_icon.setMinimumSize(QtCore.QSize(25, 25))
        self.lbl_socialmedia_icon.setMaximumSize(QtCore.QSize(25, 25))
        self.lbl_socialmedia_icon.setText("")
        self.lbl_socialmedia_icon.setObjectName("lbl_socialmedia_icon")
        self.horizontalLayout.addWidget(self.lbl_socialmedia_icon)
        self.Btn_socialmedia_del = QtWidgets.QPushButton(parent=dialog_set_socialmedia_link)
        self.Btn_socialmedia_del.setMinimumSize(QtCore.QSize(25, 25))
        self.Btn_socialmedia_del.setMaximumSize(QtCore.QSize(25, 25))
        self.Btn_socialmedia_del.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Buttons/_buttons/delete-25.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Btn_socialmedia_del.setIcon(icon)
        self.Btn_socialmedia_del.setIconSize(QtCore.QSize(25, 25))
        self.Btn_socialmedia_del.setFlat(True)
        self.Btn_socialmedia_del.setObjectName("Btn_socialmedia_del")
        self.horizontalLayout.addWidget(self.Btn_socialmedia_del)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_set_socialmedia_link)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(dialog_set_socialmedia_link)
        self.buttonBox.accepted.connect(dialog_set_socialmedia_link.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_set_socialmedia_link.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_set_socialmedia_link)

    def retranslateUi(self, dialog_set_socialmedia_link):
        _translate = QtCore.QCoreApplication.translate
        dialog_set_socialmedia_link.setWindowTitle(_translate("dialog_set_socialmedia_link", "Dialog"))
        self.Btn_socialmedia_del.setToolTip(_translate("dialog_set_socialmedia_link", "Link Button löschen"))
