# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_ui\dialog_performer_id_merge.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_performer_id_merge(object):
    def setupUi(self, dialog_performer_id_merge):
        dialog_performer_id_merge.setObjectName("dialog_performer_id_merge")
        dialog_performer_id_merge.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dialog_performer_id_merge.resize(314, 71)
        dialog_performer_id_merge.setWindowTitle("")
        dialog_performer_id_merge.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dialog_performer_id_merge)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblpic_id = QtWidgets.QLabel(parent=dialog_performer_id_merge)
        self.lblpic_id.setMinimumSize(QtCore.QSize(25, 25))
        self.lblpic_id.setMaximumSize(QtCore.QSize(25, 25))
        self.lblpic_id.setAutoFillBackground(True)
        self.lblpic_id.setStyleSheet("")
        self.lblpic_id.setText("")
        self.lblpic_id.setPixmap(QtGui.QPixmap(":/labels/_labels/id_merge.png"))
        self.lblpic_id.setScaledContents(False)
        self.lblpic_id.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblpic_id.setObjectName("lblpic_id")
        self.horizontalLayout_2.addWidget(self.lblpic_id)
        self.lblid = QtWidgets.QLabel(parent=dialog_performer_id_merge)
        self.lblid.setMinimumSize(QtCore.QSize(20, 25))
        self.lblid.setMaximumSize(QtCore.QSize(30, 25))
        self.lblid.setObjectName("lblid")
        self.horizontalLayout_2.addWidget(self.lblid)
        self.lnEdit_id = QtWidgets.QLineEdit(parent=dialog_performer_id_merge)
        self.lnEdit_id.setMinimumSize(QtCore.QSize(120, 25))
        self.lnEdit_id.setMaximumSize(QtCore.QSize(120, 25))
        self.lnEdit_id.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lnEdit_id.setObjectName("lnEdit_id")
        self.horizontalLayout_2.addWidget(self.lnEdit_id)
        self.Btn_performer_id_merge = QtWidgets.QDialogButtonBox(parent=dialog_performer_id_merge)
        self.Btn_performer_id_merge.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_performer_id_merge.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Btn_performer_id_merge.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.Btn_performer_id_merge.setCenterButtons(False)
        self.Btn_performer_id_merge.setObjectName("Btn_performer_id_merge")
        self.horizontalLayout_2.addWidget(self.Btn_performer_id_merge)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_id_db = QtWidgets.QLabel(parent=dialog_performer_id_merge)
        self.lbl_id_db.setMinimumSize(QtCore.QSize(45, 16))
        self.lbl_id_db.setMaximumSize(QtCore.QSize(20, 16))
        self.lbl_id_db.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_id_db.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_id_db.setText("")
        self.lbl_id_db.setObjectName("lbl_id_db")
        self.horizontalLayout.addWidget(self.lbl_id_db)
        self.lbl_name_db = QtWidgets.QLabel(parent=dialog_performer_id_merge)
        self.lbl_name_db.setMinimumSize(QtCore.QSize(0, 16))
        self.lbl_name_db.setMaximumSize(QtCore.QSize(16777215, 16))
        self.lbl_name_db.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_name_db.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_name_db.setText("")
        self.lbl_name_db.setObjectName("lbl_name_db")
        self.horizontalLayout.addWidget(self.lbl_name_db)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(dialog_performer_id_merge)
        self.Btn_performer_id_merge.accepted.connect(dialog_performer_id_merge.accept) # type: ignore
        self.Btn_performer_id_merge.rejected.connect(dialog_performer_id_merge.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_performer_id_merge)

    def retranslateUi(self, dialog_performer_id_merge):
        _translate = QtCore.QCoreApplication.translate
        self.lblid.setText(_translate("dialog_performer_id_merge", "ID:"))
        self.lnEdit_id.setToolTip(_translate("dialog_performer_id_merge", "<html><head/><body><p>Performer Name eingeben !</p></body></html>"))
        self.lnEdit_id.setInputMask(_translate("dialog_performer_id_merge", "99999"))
