# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_ui\dlg_daten_auswahl.ui'
#
# Created by: PyQt6 UI code generator 6.6.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dlg_daten_auswahl(object):
    def setupUi(self, Dlg_daten_auswahl):
        Dlg_daten_auswahl.setObjectName("Dlg_daten_auswahl")
        Dlg_daten_auswahl.resize(840, 709)
        Dlg_daten_auswahl.setToolTip("")
        Dlg_daten_auswahl.setModal(True)
        self.grpBox_source_1 = QtWidgets.QGroupBox(parent=Dlg_daten_auswahl)
        self.grpBox_source_1.setGeometry(QtCore.QRect(10, 10, 820, 180))
        self.grpBox_source_1.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"border-radius: 5px;")
        self.grpBox_source_1.setTitle("")
        self.grpBox_source_1.setObjectName("grpBox_source_1")
        self.Btn_daten_1 = QtWidgets.QPushButton(parent=self.grpBox_source_1)
        self.Btn_daten_1.setGeometry(QtCore.QRect(20, 20, 781, 140))
        self.Btn_daten_1.setSizeIncrement(QtCore.QSize(20, 10))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Btn_daten_1.setFont(font)
        self.Btn_daten_1.setStyleSheet("QPushButton { \n"
"    background-color: rgb(255, 253, 213);}\n"
"QPushButton:focus {\n"
"    border: 2px inset rgb(85, 170, 255);}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(49, 50, 62);}")
        self.Btn_daten_1.setText("")
        self.Btn_daten_1.setAutoDefault(True)
        self.Btn_daten_1.setDefault(True)
        self.Btn_daten_1.setObjectName("Btn_daten_1")
        self.grpBox_source_2 = QtWidgets.QGroupBox(parent=Dlg_daten_auswahl)
        self.grpBox_source_2.setGeometry(QtCore.QRect(10, 220, 821, 181))
        self.grpBox_source_2.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"border-radius: 5px;")
        self.grpBox_source_2.setTitle("")
        self.grpBox_source_2.setObjectName("grpBox_source_2")
        self.Btn_daten_2 = QtWidgets.QPushButton(parent=self.grpBox_source_2)
        self.Btn_daten_2.setGeometry(QtCore.QRect(20, 30, 781, 140))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.Btn_daten_2.setFont(font)
        self.Btn_daten_2.setStyleSheet("QPushButton { \n"
"    background-color: rgb(255, 253, 213);}\n"
"QPushButton:focus {\n"
"    border: 2px inset rgb(85, 170, 255);}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(49, 50, 62);}")
        self.Btn_daten_2.setText("")
        self.Btn_daten_2.setObjectName("Btn_daten_2")
        self.Btn_Abbruch = QtWidgets.QPushButton(parent=Dlg_daten_auswahl)
        self.Btn_Abbruch.setGeometry(QtCore.QRect(694, 660, 111, 23))
        self.Btn_Abbruch.setObjectName("Btn_Abbruch")
        self.grpBox_source_3 = QtWidgets.QGroupBox(parent=Dlg_daten_auswahl)
        self.grpBox_source_3.setGeometry(QtCore.QRect(10, 430, 821, 181))
        self.grpBox_source_3.setStyleSheet("background-color: rgb(211, 211, 211);\n"
"border-radius: 5px;")
        self.grpBox_source_3.setTitle("")
        self.grpBox_source_3.setObjectName("grpBox_source_3")
        self.Btn_daten_3 = QtWidgets.QPushButton(parent=self.grpBox_source_3)
        self.Btn_daten_3.setGeometry(QtCore.QRect(20, 30, 781, 140))
        self.Btn_daten_3.setStyleSheet("QPushButton { \n"
"    background-color: rgb(255, 253, 213);}\n"
"QPushButton:focus {\n"
"    border: 2px inset rgb(85, 170, 255);}\n"
"QPushButton:hover {\n"
"    border: 2px solid rgb(49, 50, 62);}")
        self.Btn_daten_3.setText("")
        self.Btn_daten_3.setObjectName("Btn_daten_3")

        self.retranslateUi(Dlg_daten_auswahl)
        QtCore.QMetaObject.connectSlotsByName(Dlg_daten_auswahl)

    def retranslateUi(self, Dlg_daten_auswahl):
        _translate = QtCore.QCoreApplication.translate
        Dlg_daten_auswahl.setWindowTitle(_translate("Dlg_daten_auswahl", "Auswahl für:"))
        self.Btn_Abbruch.setText(_translate("Dlg_daten_auswahl", "Abbruch"))
