# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_performer_add.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_performer_add(object):
    def setupUi(self, dialog_performer_add):
        dialog_performer_add.setObjectName("dialog_performer_add")
        dialog_performer_add.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dialog_performer_add.resize(419, 146)
        dialog_performer_add.setWindowTitle("")
        dialog_performer_add.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dialog_performer_add)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblpic_name = QtWidgets.QLabel(parent=dialog_performer_add)
        self.lblpic_name.setMinimumSize(QtCore.QSize(25, 25))
        self.lblpic_name.setMaximumSize(QtCore.QSize(25, 25))
        self.lblpic_name.setAutoFillBackground(True)
        self.lblpic_name.setStyleSheet("")
        self.lblpic_name.setText("")
        self.lblpic_name.setPixmap(QtGui.QPixmap(":/labels/_labels/nutzer.png"))
        self.lblpic_name.setScaledContents(False)
        self.lblpic_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblpic_name.setObjectName("lblpic_name")
        self.horizontalLayout_2.addWidget(self.lblpic_name)
        self.lblname = QtWidgets.QLabel(parent=dialog_performer_add)
        self.lblname.setMinimumSize(QtCore.QSize(50, 25))
        self.lblname.setMaximumSize(QtCore.QSize(50, 25))
        self.lblname.setObjectName("lblname")
        self.horizontalLayout_2.addWidget(self.lblname)
        self.lnEdit_name = QtWidgets.QLineEdit(parent=dialog_performer_add)
        self.lnEdit_name.setMinimumSize(QtCore.QSize(300, 25))
        self.lnEdit_name.setMaximumSize(QtCore.QSize(300, 25))
        self.lnEdit_name.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lnEdit_name.setObjectName("lnEdit_name")
        self.horizontalLayout_2.addWidget(self.lnEdit_name)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.lay_ordner = QtWidgets.QHBoxLayout()
        self.lay_ordner.setObjectName("lay_ordner")
        self.lblpic_ordner = QtWidgets.QLabel(parent=dialog_performer_add)
        self.lblpic_ordner.setMinimumSize(QtCore.QSize(25, 25))
        self.lblpic_ordner.setMaximumSize(QtCore.QSize(25, 25))
        self.lblpic_ordner.setText("")
        self.lblpic_ordner.setPixmap(QtGui.QPixmap(":/labels/_labels/ordner.png"))
        self.lblpic_ordner.setScaledContents(False)
        self.lblpic_ordner.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblpic_ordner.setObjectName("lblpic_ordner")
        self.lay_ordner.addWidget(self.lblpic_ordner)
        self.lblordner = QtWidgets.QLabel(parent=dialog_performer_add)
        self.lblordner.setMinimumSize(QtCore.QSize(50, 25))
        self.lblordner.setMaximumSize(QtCore.QSize(50, 25))
        self.lblordner.setObjectName("lblordner")
        self.lay_ordner.addWidget(self.lblordner)
        self.lnEdit_ordner = QtWidgets.QLineEdit(parent=dialog_performer_add)
        self.lnEdit_ordner.setMinimumSize(QtCore.QSize(300, 25))
        self.lnEdit_ordner.setMaximumSize(QtCore.QSize(300, 25))
        self.lnEdit_ordner.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lnEdit_ordner.setObjectName("lnEdit_ordner")
        self.lay_ordner.addWidget(self.lnEdit_ordner)
        self.gridLayout.addLayout(self.lay_ordner, 1, 0, 1, 1)
        self.lay_gender = QtWidgets.QHBoxLayout()
        self.lay_gender.setObjectName("lay_gender")
        self.lblpic_ordner_2 = QtWidgets.QLabel(parent=dialog_performer_add)
        self.lblpic_ordner_2.setMinimumSize(QtCore.QSize(25, 25))
        self.lblpic_ordner_2.setMaximumSize(QtCore.QSize(25, 25))
        self.lblpic_ordner_2.setText("")
        self.lblpic_ordner_2.setPixmap(QtGui.QPixmap(":/labels/_labels/geschlecht.png"))
        self.lblpic_ordner_2.setScaledContents(False)
        self.lblpic_ordner_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblpic_ordner_2.setObjectName("lblpic_ordner_2")
        self.lay_gender.addWidget(self.lblpic_ordner_2)
        self.lblordner_2 = QtWidgets.QLabel(parent=dialog_performer_add)
        self.lblordner_2.setMinimumSize(QtCore.QSize(50, 25))
        self.lblordner_2.setMaximumSize(QtCore.QSize(50, 25))
        self.lblordner_2.setObjectName("lblordner_2")
        self.lay_gender.addWidget(self.lblordner_2)
        self.cBox_performer_gender = QtWidgets.QComboBox(parent=dialog_performer_add)
        self.cBox_performer_gender.setObjectName("cBox_performer_gender")
        self.cBox_performer_gender.addItem("")
        self.cBox_performer_gender.addItem("")
        self.cBox_performer_gender.addItem("")
        self.lay_gender.addWidget(self.cBox_performer_gender)
        self.gridLayout.addLayout(self.lay_gender, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_name_db = QtWidgets.QLabel(parent=dialog_performer_add)
        self.lbl_name_db.setMinimumSize(QtCore.QSize(300, 20))
        self.lbl_name_db.setMaximumSize(QtCore.QSize(300, 20))
        self.lbl_name_db.setText("")
        self.lbl_name_db.setObjectName("lbl_name_db")
        self.horizontalLayout.addWidget(self.lbl_name_db)
        self.Btn_performer_add = QtWidgets.QDialogButtonBox(parent=dialog_performer_add)
        self.Btn_performer_add.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_performer_add.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Btn_performer_add.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.Btn_performer_add.setCenterButtons(False)
        self.Btn_performer_add.setObjectName("Btn_performer_add")
        self.horizontalLayout.addWidget(self.Btn_performer_add)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)

        self.retranslateUi(dialog_performer_add)
        self.Btn_performer_add.accepted.connect(dialog_performer_add.accept) # type: ignore
        self.Btn_performer_add.rejected.connect(dialog_performer_add.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_performer_add)

    def retranslateUi(self, dialog_performer_add):
        _translate = QtCore.QCoreApplication.translate
        self.lblname.setText(_translate("dialog_performer_add", "Name:"))
        self.lnEdit_name.setToolTip(_translate("dialog_performer_add", "<html><head/><body><p>Performer Name eingeben !</p></body></html>"))
        self.lblordner.setText(_translate("dialog_performer_add", "Ordner:"))
        self.lblordner_2.setText(_translate("dialog_performer_add", "Gender:"))
        self.cBox_performer_gender.setItemText(0, _translate("dialog_performer_add", "weiblich"))
        self.cBox_performer_gender.setItemText(1, _translate("dialog_performer_add", "männlich"))
        self.cBox_performer_gender.setItemText(2, _translate("dialog_performer_add", "transsexuel"))
