# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_auswahl_buttons.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(550, 237)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pushButton_2 = QtWidgets.QPushButton(parent=Dialog)
        self.pushButton_2.setMinimumSize(QtCore.QSize(20, 20))
        self.pushButton_2.setMaximumSize(QtCore.QSize(20, 20))
        self.pushButton_2.setAutoFillBackground(True)
        self.pushButton_2.setStyleSheet("background-image: url(:/labels/_labels/fenster-schliessen.png);")
        self.pushButton_2.setText("")
        self.pushButton_2.setFlat(True)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gBox_auswahl_1 = QtWidgets.QGroupBox(parent=Dialog)
        self.gBox_auswahl_1.setMinimumSize(QtCore.QSize(530, 160))
        self.gBox_auswahl_1.setObjectName("gBox_auswahl_1")
        self.pushButton = QWordWarpButton(parent=self.gBox_auswahl_1)
        self.pushButton.setGeometry(QtCore.QRect(0, 20, 530, 140))
        self.pushButton.setStyleSheet("QLabel,QPushButton { \n"
"background-color: #FFFDD5;}\n"
"QLabel:hover,QPushButton:hover {\n"
"border: 2px solid rgb(49, 50, 62);}\n"
"QLabel:focus,QPushButton:focus {\n"
"border: 2px inset rgb(85, 170, 255);}\n"
"QToolTip {min-width: 350px;}")
        self.pushButton.setText("")
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout.addWidget(self.gBox_auswahl_1)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.gBox_auswahl_1.raise_()
        self.buttonBox.raise_()
        self.pushButton_2.raise_()

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pushButton_2.setToolTip(_translate("Dialog", "Fenster schliessen"))
        self.gBox_auswahl_1.setTitle(_translate("Dialog", "Titel"))
from gui.custom_wordwrap_button.py import QWordWarpButton
