# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dialog_performer_add_from_link.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_performer_add_from_link(object):
    def setupUi(self, dialog_performer_add_from_link):
        dialog_performer_add_from_link.setObjectName("dialog_performer_add_from_link")
        dialog_performer_add_from_link.setWindowModality(QtCore.Qt.WindowModality.ApplicationModal)
        dialog_performer_add_from_link.resize(428, 262)
        dialog_performer_add_from_link.setWindowTitle("")
        dialog_performer_add_from_link.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dialog_performer_add_from_link)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblpic_name = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lblpic_name.setMinimumSize(QtCore.QSize(25, 25))
        self.lblpic_name.setMaximumSize(QtCore.QSize(25, 25))
        self.lblpic_name.setAutoFillBackground(True)
        self.lblpic_name.setStyleSheet("")
        self.lblpic_name.setText("")
        self.lblpic_name.setPixmap(QtGui.QPixmap(":/labels/_labels/nutzer.png"))
        self.lblpic_name.setScaledContents(False)
        self.lblpic_name.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblpic_name.setObjectName("lblpic_name")
        self.horizontalLayout_2.addWidget(self.lblpic_name)
        self.lbl_name = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_name.setMinimumSize(QtCore.QSize(40, 25))
        self.lbl_name.setMaximumSize(QtCore.QSize(30, 25))
        self.lbl_name.setObjectName("lbl_name")
        self.horizontalLayout_2.addWidget(self.lbl_name)
        self.lnEdit_name = QtWidgets.QLineEdit(parent=dialog_performer_add_from_link)
        self.lnEdit_name.setMinimumSize(QtCore.QSize(330, 25))
        self.lnEdit_name.setMaximumSize(QtCore.QSize(300, 25))
        self.lnEdit_name.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lnEdit_name.setInputMask("")
        self.lnEdit_name.setObjectName("lnEdit_name")
        self.horizontalLayout_2.addWidget(self.lnEdit_name)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.lblpic_ordner = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lblpic_ordner.setMinimumSize(QtCore.QSize(25, 25))
        self.lblpic_ordner.setMaximumSize(QtCore.QSize(25, 25))
        self.lblpic_ordner.setAutoFillBackground(True)
        self.lblpic_ordner.setStyleSheet("")
        self.lblpic_ordner.setText("")
        self.lblpic_ordner.setPixmap(QtGui.QPixmap(":/labels/_labels/ordner.png"))
        self.lblpic_ordner.setScaledContents(False)
        self.lblpic_ordner.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblpic_ordner.setObjectName("lblpic_ordner")
        self.horizontalLayout_3.addWidget(self.lblpic_ordner)
        self.lbl_ordner = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_ordner.setMinimumSize(QtCore.QSize(40, 25))
        self.lbl_ordner.setMaximumSize(QtCore.QSize(30, 25))
        self.lbl_ordner.setObjectName("lbl_ordner")
        self.horizontalLayout_3.addWidget(self.lbl_ordner)
        self.lnEdit_ordner = QtWidgets.QLineEdit(parent=dialog_performer_add_from_link)
        self.lnEdit_ordner.setMinimumSize(QtCore.QSize(330, 25))
        self.lnEdit_ordner.setMaximumSize(QtCore.QSize(300, 25))
        self.lnEdit_ordner.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lnEdit_ordner.setInputMask("")
        self.lnEdit_ordner.setObjectName("lnEdit_ordner")
        self.horizontalLayout_3.addWidget(self.lnEdit_ordner)
        self.gridLayout.addLayout(self.horizontalLayout_3, 1, 0, 1, 1)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lblpic_ordner_2 = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lblpic_ordner_2.setMinimumSize(QtCore.QSize(30, 20))
        self.lblpic_ordner_2.setMaximumSize(QtCore.QSize(30, 25))
        self.lblpic_ordner_2.setAutoFillBackground(True)
        self.lblpic_ordner_2.setStyleSheet("")
        self.lblpic_ordner_2.setText("")
        self.lblpic_ordner_2.setPixmap(QtGui.QPixmap(":/labels/_labels/IAFD.jpg"))
        self.lblpic_ordner_2.setScaledContents(False)
        self.lblpic_ordner_2.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.lblpic_ordner_2.setObjectName("lblpic_ordner_2")
        self.horizontalLayout_4.addWidget(self.lblpic_ordner_2)
        self.lnEdit_iafdlink = QtWidgets.QLineEdit(parent=dialog_performer_add_from_link)
        self.lnEdit_iafdlink.setMinimumSize(QtCore.QSize(360, 25))
        self.lnEdit_iafdlink.setMaximumSize(QtCore.QSize(300, 25))
        self.lnEdit_iafdlink.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lnEdit_iafdlink.setInputMask("")
        self.lnEdit_iafdlink.setObjectName("lnEdit_iafdlink")
        self.horizontalLayout_4.addWidget(self.lnEdit_iafdlink)
        self.gridLayout.addLayout(self.horizontalLayout_4, 2, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_name_db = QtWidgets.QLabel(parent=dialog_performer_add_from_link)
        self.lbl_name_db.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_name_db.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_name_db.setText("")
        self.lbl_name_db.setObjectName("lbl_name_db")
        self.horizontalLayout.addWidget(self.lbl_name_db)
        self.Btn_performer_id_merge = QtWidgets.QDialogButtonBox(parent=dialog_performer_add_from_link)
        self.Btn_performer_id_merge.setMinimumSize(QtCore.QSize(100, 0))
        self.Btn_performer_id_merge.setMaximumSize(QtCore.QSize(100, 16777215))
        self.Btn_performer_id_merge.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_performer_id_merge.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Btn_performer_id_merge.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.Btn_performer_id_merge.setCenterButtons(False)
        self.Btn_performer_id_merge.setObjectName("Btn_performer_id_merge")
        self.horizontalLayout.addWidget(self.Btn_performer_id_merge)
        self.gridLayout.addLayout(self.horizontalLayout, 3, 0, 1, 1)
        self.tblWdg_datenbank = QtWidgets.QTableWidget(parent=dialog_performer_add_from_link)
        self.tblWdg_datenbank.setMinimumSize(QtCore.QSize(410, 110))
        self.tblWdg_datenbank.setMaximumSize(QtCore.QSize(410, 110))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tblWdg_datenbank.setFont(font)
        self.tblWdg_datenbank.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.tblWdg_datenbank.setObjectName("tblWdg_datenbank")
        self.tblWdg_datenbank.setColumnCount(3)
        self.tblWdg_datenbank.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        item.setBackground(QtGui.QColor(251, 255, 201))
        self.tblWdg_datenbank.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tblWdg_datenbank.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(7)
        item.setFont(font)
        self.tblWdg_datenbank.setHorizontalHeaderItem(2, item)
        self.tblWdg_datenbank.horizontalHeader().setDefaultSectionSize(80)
        self.tblWdg_datenbank.horizontalHeader().setMinimumSectionSize(16)
        self.gridLayout.addWidget(self.tblWdg_datenbank, 4, 0, 1, 1)

        self.retranslateUi(dialog_performer_add_from_link)
        self.Btn_performer_id_merge.accepted.connect(dialog_performer_add_from_link.accept) # type: ignore
        self.Btn_performer_id_merge.rejected.connect(dialog_performer_add_from_link.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_performer_add_from_link)

    def retranslateUi(self, dialog_performer_add_from_link):
        _translate = QtCore.QCoreApplication.translate
        self.lbl_name.setText(_translate("dialog_performer_add_from_link", "Name:"))
        self.lnEdit_name.setToolTip(_translate("dialog_performer_add_from_link", "<html><head/><body><p>Performer Name eingeben !</p></body></html>"))
        self.lbl_ordner.setText(_translate("dialog_performer_add_from_link", "Ordner:"))
        self.lnEdit_ordner.setToolTip(_translate("dialog_performer_add_from_link", "<html><head/><body><p>Performer Name eingeben !</p></body></html>"))
        self.lnEdit_iafdlink.setToolTip(_translate("dialog_performer_add_from_link", "<html><head/><body><p>Performer Name eingeben !</p></body></html>"))
        item = self.tblWdg_datenbank.horizontalHeaderItem(0)
        item.setText(_translate("dialog_performer_add_from_link", "ID"))
        item = self.tblWdg_datenbank.horizontalHeaderItem(1)
        item.setText(_translate("dialog_performer_add_from_link", "Name"))
        item = self.tblWdg_datenbank.horizontalHeaderItem(2)
        item.setText(_translate("dialog_performer_add_from_link", "Ordner"))
