# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dlg_gender_auswahl.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(295, 105)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Btn_female = QtWidgets.QPushButton(parent=Dialog)
        self.Btn_female.setAutoFillBackground(True)
        self.Btn_female.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Buttons/_buttons/gender/weiblich-75.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Btn_female.setIcon(icon)
        self.Btn_female.setIconSize(QtCore.QSize(75, 75))
        self.Btn_female.setObjectName("Btn_female")
        self.horizontalLayout.addWidget(self.Btn_female)
        self.Btn_male = QtWidgets.QPushButton(parent=Dialog)
        self.Btn_male.setAutoFillBackground(True)
        self.Btn_male.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Buttons/_buttons/gender/maennlich-75.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Btn_male.setIcon(icon1)
        self.Btn_male.setIconSize(QtCore.QSize(75, 75))
        self.Btn_male.setObjectName("Btn_male")
        self.horizontalLayout.addWidget(self.Btn_male)
        self.Btn_trans = QtWidgets.QPushButton(parent=Dialog)
        self.Btn_trans.setAutoFillBackground(True)
        self.Btn_trans.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Buttons/_buttons/gender/transgender-75.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Btn_trans.setIcon(icon2)
        self.Btn_trans.setIconSize(QtCore.QSize(75, 75))
        self.Btn_trans.setObjectName("Btn_trans")
        self.horizontalLayout.addWidget(self.Btn_trans)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.Btn_female.setToolTip(_translate("Dialog", "Auswahl: weiblich"))
        self.Btn_male.setToolTip(_translate("Dialog", "Auswahl: männlich"))
        self.Btn_trans.setToolTip(_translate("Dialog", "Auswahl: weiblich"))
