# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\dlg_nations_auswahl.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(451, 73)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.cBox_nations = CustomComboBoxCheck(parent=Dialog)
        self.cBox_nations.setMinimumSize(QtCore.QSize(100, 0))
        self.cBox_nations.setEditable(False)
        self.cBox_nations.setObjectName("cBox_nations")
        self.verticalLayout.addWidget(self.cBox_nations)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_nation_1 = QtWidgets.QLabel(parent=Dialog)
        self.lbl_nation_1.setMinimumSize(QtCore.QSize(33, 25))
        self.lbl_nation_1.setMaximumSize(QtCore.QSize(33, 25))
        self.lbl_nation_1.setText("")
        self.lbl_nation_1.setObjectName("lbl_nation_1")
        self.horizontalLayout.addWidget(self.lbl_nation_1)
        self.lbl_nation_2 = QtWidgets.QLabel(parent=Dialog)
        self.lbl_nation_2.setMinimumSize(QtCore.QSize(33, 25))
        self.lbl_nation_2.setMaximumSize(QtCore.QSize(33, 25))
        self.lbl_nation_2.setText("")
        self.lbl_nation_2.setObjectName("lbl_nation_2")
        self.horizontalLayout.addWidget(self.lbl_nation_2)
        self.lbl_nation_3 = QtWidgets.QLabel(parent=Dialog)
        self.lbl_nation_3.setMinimumSize(QtCore.QSize(33, 25))
        self.lbl_nation_3.setMaximumSize(QtCore.QSize(33, 25))
        self.lbl_nation_3.setText("")
        self.lbl_nation_3.setObjectName("lbl_nation_3")
        self.horizontalLayout.addWidget(self.lbl_nation_3)
        self.lbl_nation_4 = QtWidgets.QLabel(parent=Dialog)
        self.lbl_nation_4.setMinimumSize(QtCore.QSize(33, 25))
        self.lbl_nation_4.setMaximumSize(QtCore.QSize(33, 25))
        self.lbl_nation_4.setStyleSheet("")
        self.lbl_nation_4.setText("")
        self.lbl_nation_4.setObjectName("lbl_nation_4")
        self.horizontalLayout.addWidget(self.lbl_nation_4)
        self.lbl_nation_5 = QtWidgets.QLabel(parent=Dialog)
        self.lbl_nation_5.setMinimumSize(QtCore.QSize(33, 25))
        self.lbl_nation_5.setMaximumSize(QtCore.QSize(33, 25))
        self.lbl_nation_5.setText("")
        self.lbl_nation_5.setObjectName("lbl_nation_5")
        self.horizontalLayout.addWidget(self.lbl_nation_5)
        self.lbl_nation_6 = QtWidgets.QLabel(parent=Dialog)
        self.lbl_nation_6.setMinimumSize(QtCore.QSize(33, 25))
        self.lbl_nation_6.setMaximumSize(QtCore.QSize(33, 25))
        self.lbl_nation_6.setText("")
        self.lbl_nation_6.setObjectName("lbl_nation_6")
        self.horizontalLayout.addWidget(self.lbl_nation_6)
        self.lbl_nation_7 = QtWidgets.QLabel(parent=Dialog)
        self.lbl_nation_7.setMinimumSize(QtCore.QSize(33, 25))
        self.lbl_nation_7.setMaximumSize(QtCore.QSize(33, 25))
        self.lbl_nation_7.setText("")
        self.lbl_nation_7.setObjectName("lbl_nation_7")
        self.horizontalLayout.addWidget(self.lbl_nation_7)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 25))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.gridLayout.addLayout(self.verticalLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
from gui.custom_cBox_check import CustomComboBoxCheck
