# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\einstellungen.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dlg_Einstellungen(object):
    def setupUi(self, dlg_Einstellungen):
        dlg_Einstellungen.setObjectName("dlg_Einstellungen")
        dlg_Einstellungen.resize(373, 265)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(dlg_Einstellungen.sizePolicy().hasHeightForWidth())
        dlg_Einstellungen.setSizePolicy(sizePolicy)
        dlg_Einstellungen.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        dlg_Einstellungen.setModal(True)
        self.Btn_OK = QtWidgets.QPushButton(parent=dlg_Einstellungen)
        self.Btn_OK.setGeometry(QtCore.QRect(290, 230, 75, 23))
        self.Btn_OK.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_OK.setObjectName("Btn_OK")
        self.layoutWidget = QtWidgets.QWidget(parent=dlg_Einstellungen)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 10, 351, 211))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.chkBox_InfosExifTool = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.chkBox_InfosExifTool.setObjectName("chkBox_InfosExifTool")
        self.verticalLayout.addWidget(self.chkBox_InfosExifTool)
        self.chkBox_WebScraping = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.chkBox_WebScraping.setObjectName("chkBox_WebScraping")
        self.verticalLayout.addWidget(self.chkBox_WebScraping)
        self.chkBox_Speichern = QtWidgets.QCheckBox(parent=self.layoutWidget)
        self.chkBox_Speichern.setObjectName("chkBox_Speichern")
        self.verticalLayout.addWidget(self.chkBox_Speichern)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox_tpdb_image_counter = QtWidgets.QSpinBox(parent=self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.spinBox_tpdb_image_counter.sizePolicy().hasHeightForWidth())
        self.spinBox_tpdb_image_counter.setSizePolicy(sizePolicy)
        self.spinBox_tpdb_image_counter.setMinimumSize(QtCore.QSize(40, 25))
        self.spinBox_tpdb_image_counter.setMaximumSize(QtCore.QSize(40, 25))
        self.spinBox_tpdb_image_counter.setObjectName("spinBox_tpdb_image_counter")
        self.horizontalLayout.addWidget(self.spinBox_tpdb_image_counter)
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setMinimumSize(QtCore.QSize(0, 25))
        self.label.setMaximumSize(QtCore.QSize(16777215, 25))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.lbl_LastDIR = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lbl_LastDIR.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_LastDIR.setMaximumSize(QtCore.QSize(16777215, 20))
        self.lbl_LastDIR.setStyleSheet("background-color: #FFFDD5;")
        self.lbl_LastDIR.setText("")
        self.lbl_LastDIR.setObjectName("lbl_LastDIR")
        self.verticalLayout_2.addWidget(self.lbl_LastDIR)
        self.groupBox = QtWidgets.QGroupBox(parent=self.layoutWidget)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 55))
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 55))
        self.groupBox.setObjectName("groupBox")
        self.lnEdit_theporndb_apikey = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lnEdit_theporndb_apikey.setGeometry(QtCore.QRect(10, 20, 331, 20))
        self.lnEdit_theporndb_apikey.setStyleSheet("background-color: #FFFDD5;")
        self.lnEdit_theporndb_apikey.setText("")
        self.lnEdit_theporndb_apikey.setObjectName("lnEdit_theporndb_apikey")
        self.verticalLayout_2.addWidget(self.groupBox)
        self.layoutWidget.raise_()
        self.Btn_OK.raise_()

        self.retranslateUi(dlg_Einstellungen)
        QtCore.QMetaObject.connectSlotsByName(dlg_Einstellungen)

    def retranslateUi(self, dlg_Einstellungen):
        _translate = QtCore.QCoreApplication.translate
        dlg_Einstellungen.setWindowTitle(_translate("dlg_Einstellungen", "Einstellungen"))
        self.Btn_OK.setText(_translate("dlg_Einstellungen", "OK"))
        self.chkBox_InfosExifTool.setText(_translate("dlg_Einstellungen", "nach Datei laden, Infos laden(ExifTool)"))
        self.chkBox_WebScraping.setText(_translate("dlg_Einstellungen", "nach Laden, Webscraping"))
        self.chkBox_Speichern.setText(_translate("dlg_Einstellungen", "Einstellungen speichern"))
        self.label.setText(_translate("dlg_Einstellungen", "Azahl der Bilder download von API TPDB"))
        self.groupBox.setTitle(_translate("dlg_Einstellungen", " The Porn DB API-Key:"))
