# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\rename.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(490, 375)
        Dialog.setStyleSheet("background-color: rgb(255, 255, 255);")
        Dialog.setModal(True)
        self.lbl_Rename = QtWidgets.QLabel(parent=Dialog)
        self.lbl_Rename.setGeometry(QtCore.QRect(0, 0, 481, 281))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.lbl_Rename.sizePolicy().hasHeightForWidth())
        self.lbl_Rename.setSizePolicy(sizePolicy)
        self.lbl_Rename.setStyleSheet("background-image: url(:/labels/_labels/dialog_windows/rename.png);")
        self.lbl_Rename.setText("")
        self.lbl_Rename.setScaledContents(True)
        self.lbl_Rename.setObjectName("lbl_Rename")
        self.Btn_OK_Abbruch = QtWidgets.QDialogButtonBox(parent=Dialog)
        self.Btn_OK_Abbruch.setGeometry(QtCore.QRect(210, 340, 101, 31))
        self.Btn_OK_Abbruch.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 12pt \"MS Shell Dlg 2\";\n"
"    border-radius: 4px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_OK_Abbruch.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.Btn_OK_Abbruch.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.Btn_OK_Abbruch.setObjectName("Btn_OK_Abbruch")
        self.groupBox = QtWidgets.QGroupBox(parent=Dialog)
        self.groupBox.setGeometry(QtCore.QRect(10, 290, 471, 51))
        self.groupBox.setStyleSheet("QGroupBox {\n"
"background-color: rgb(218, 222, 226);\n"
"border: 1px solid grey;border-radius: 5px;}")
        self.groupBox.setObjectName("groupBox")
        self.lnEdit_Rename = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lnEdit_Rename.setGeometry(QtCore.QRect(10, 20, 471, 22))
        self.lnEdit_Rename.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lnEdit_Rename.setObjectName("lnEdit_Rename")
        self.groupBox.raise_()
        self.lbl_Rename.raise_()
        self.Btn_OK_Abbruch.raise_()

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Datei umbennen !"))
        self.groupBox.setTitle(_translate("Dialog", "zu unbennende Dateiname:"))
