# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\spidermonitor.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_spider_monitor(object):
    def setupUi(self, spider_monitor):
        spider_monitor.setObjectName("spider_monitor")
        spider_monitor.resize(565, 605)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        spider_monitor.setFont(font)
        self.tblWdg_urls = QtWidgets.QTableWidget(parent=spider_monitor)
        self.tblWdg_urls.setGeometry(QtCore.QRect(10, 110, 540, 400))
        self.tblWdg_urls.setMinimumSize(QtCore.QSize(400, 0))
        self.tblWdg_urls.setMaximumSize(QtCore.QSize(1000, 16777207))
        font = QtGui.QFont()
        font.setPointSize(7)
        self.tblWdg_urls.setFont(font)
        self.tblWdg_urls.setContextMenuPolicy(QtCore.Qt.ContextMenuPolicy.CustomContextMenu)
        self.tblWdg_urls.setStyleSheet("background-color: rgb(255, 253, 213);\n"
"border: 1px solid grey;border-radius: 5px;\n"
"")
        self.tblWdg_urls.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tblWdg_urls.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.SelectedClicked)
        self.tblWdg_urls.setObjectName("tblWdg_urls")
        self.tblWdg_urls.setColumnCount(1)
        self.tblWdg_urls.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        item.setTextAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignTop)
        font = QtGui.QFont()
        font.setPointSize(6)
        item.setFont(font)
        self.tblWdg_urls.setHorizontalHeaderItem(0, item)
        self.tblWdg_urls.horizontalHeader().setDefaultSectionSize(540)
        self.tblWdg_urls.horizontalHeader().setMinimumSectionSize(540)
        self.tblWdg_urls.verticalHeader().setDefaultSectionSize(16)
        self.tblWdg_urls.verticalHeader().setMinimumSectionSize(16)
        self.grpBox_datensatz = QtWidgets.QGroupBox(parent=spider_monitor)
        self.grpBox_datensatz.setGeometry(QtCore.QRect(10, 10, 181, 51))
        self.grpBox_datensatz.setObjectName("grpBox_datensatz")
        self.layoutWidget = QtWidgets.QWidget(parent=self.grpBox_datensatz)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 168, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lbl_pages = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lbl_pages.setMinimumSize(QtCore.QSize(80, 20))
        self.lbl_pages.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_pages.setText("")
        self.lbl_pages.setObjectName("lbl_pages")
        self.horizontalLayout.addWidget(self.lbl_pages)
        self.lbldatensatz_end = QtWidgets.QLabel(parent=self.layoutWidget)
        self.lbldatensatz_end.setMinimumSize(QtCore.QSize(80, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbldatensatz_end.setFont(font)
        self.lbldatensatz_end.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbldatensatz_end.setLineWidth(5)
        self.lbldatensatz_end.setObjectName("lbldatensatz_end")
        self.horizontalLayout.addWidget(self.lbldatensatz_end)
        self.grpBox_pages = QtWidgets.QGroupBox(parent=spider_monitor)
        self.grpBox_pages.setGeometry(QtCore.QRect(200, 10, 101, 51))
        self.grpBox_pages.setObjectName("grpBox_pages")
        self.lbl_datensatz = QtWidgets.QLabel(parent=self.grpBox_pages)
        self.lbl_datensatz.setGeometry(QtCore.QRect(10, 20, 80, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_datensatz.setFont(font)
        self.lbl_datensatz.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_datensatz.setText("")
        self.lbl_datensatz.setObjectName("lbl_datensatz")
        self.grpBox_error = QtWidgets.QGroupBox(parent=spider_monitor)
        self.grpBox_error.setGeometry(QtCore.QRect(310, 10, 71, 51))
        self.grpBox_error.setObjectName("grpBox_error")
        self.lbl_error = QtWidgets.QLabel(parent=self.grpBox_error)
        self.lbl_error.setGeometry(QtCore.QRect(10, 20, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_error.setFont(font)
        self.lbl_error.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_error.setText("")
        self.lbl_error.setObjectName("lbl_error")
        self.grpBox_neu = QtWidgets.QGroupBox(parent=spider_monitor)
        self.grpBox_neu.setGeometry(QtCore.QRect(390, 10, 71, 51))
        self.grpBox_neu.setObjectName("grpBox_neu")
        self.lbl_neu = QtWidgets.QLabel(parent=self.grpBox_neu)
        self.lbl_neu.setGeometry(QtCore.QRect(10, 20, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_neu.setFont(font)
        self.lbl_neu.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_neu.setText("")
        self.lbl_neu.setObjectName("lbl_neu")
        self.grpBox_update = QtWidgets.QGroupBox(parent=spider_monitor)
        self.grpBox_update.setGeometry(QtCore.QRect(470, 10, 71, 51))
        self.grpBox_update.setObjectName("grpBox_update")
        self.lbl_update = QtWidgets.QLabel(parent=self.grpBox_update)
        self.lbl_update.setGeometry(QtCore.QRect(10, 20, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lbl_update.setFont(font)
        self.lbl_update.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_update.setText("")
        self.lbl_update.setObjectName("lbl_update")
        self.layoutWidget1 = QtWidgets.QWidget(parent=spider_monitor)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 76, 361, 22))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lblZeit = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lblZeit.sizePolicy().hasHeightForWidth())
        self.lblZeit.setSizePolicy(sizePolicy)
        self.lblZeit.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.lblZeit.setFont(font)
        self.lblZeit.setObjectName("lblZeit")
        self.horizontalLayout_2.addWidget(self.lblZeit)
        self.lbl_time = QtWidgets.QLabel(parent=self.layoutWidget1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lbl_time.sizePolicy().hasHeightForWidth())
        self.lbl_time.setSizePolicy(sizePolicy)
        self.lbl_time.setMinimumSize(QtCore.QSize(200, 20))
        self.lbl_time.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_time.setText("")
        self.lbl_time.setObjectName("lbl_time")
        self.horizontalLayout_2.addWidget(self.lbl_time)
        self.lbl_counter = QtWidgets.QLabel(parent=self.layoutWidget1)
        self.lbl_counter.setMinimumSize(QtCore.QSize(0, 20))
        self.lbl_counter.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_counter.setText("")
        self.lbl_counter.setObjectName("lbl_counter")
        self.horizontalLayout_2.addWidget(self.lbl_counter)
        self.layoutWidget2 = QtWidgets.QWidget(parent=spider_monitor)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 550, 541, 41))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Btn_break = QtWidgets.QPushButton(parent=self.layoutWidget2)
        self.Btn_break.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_break.sizePolicy().hasHeightForWidth())
        self.Btn_break.setSizePolicy(sizePolicy)
        self.Btn_break.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_break.setObjectName("Btn_break")
        self.horizontalLayout_3.addWidget(self.Btn_break)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Policy.Fixed, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.Btn_back = QtWidgets.QPushButton(parent=self.layoutWidget2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_back.sizePolicy().hasHeightForWidth())
        self.Btn_back.setSizePolicy(sizePolicy)
        self.Btn_back.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 10pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.Btn_back.setObjectName("Btn_back")
        self.horizontalLayout_3.addWidget(self.Btn_back)
        self.Btn_start = QtWidgets.QPushButton(parent=spider_monitor)
        self.Btn_start.setGeometry(QtCore.QRect(470, 80, 75, 23))
        self.Btn_start.setObjectName("Btn_start")
        self.lbl_message = QtWidgets.QLabel(parent=spider_monitor)
        self.lbl_message.setGeometry(QtCore.QRect(20, 520, 521, 16))
        self.lbl_message.setStyleSheet("background-color: rgb(255, 253, 213);")
        self.lbl_message.setText("")
        self.lbl_message.setObjectName("lbl_message")
        self.layoutWidget.raise_()
        self.layoutWidget.raise_()
        self.grpBox_pages.raise_()
        self.grpBox_datensatz.raise_()
        self.tblWdg_urls.raise_()
        self.grpBox_error.raise_()
        self.grpBox_neu.raise_()
        self.grpBox_update.raise_()
        self.Btn_start.raise_()
        self.lbl_message.raise_()

        self.retranslateUi(spider_monitor)
        QtCore.QMetaObject.connectSlotsByName(spider_monitor)

    def retranslateUi(self, spider_monitor):
        _translate = QtCore.QCoreApplication.translate
        spider_monitor.setWindowTitle(_translate("spider_monitor", "Spider:"))
        self.tblWdg_urls.setSortingEnabled(True)
        item = self.tblWdg_urls.horizontalHeaderItem(0)
        item.setText(_translate("spider_monitor", "URL"))
        self.grpBox_datensatz.setTitle(_translate("spider_monitor", "Seiten/Pages:"))
        self.lbldatensatz_end.setText(_translate("spider_monitor", "von: "))
        self.grpBox_pages.setTitle(_translate("spider_monitor", "Datensätze:"))
        self.grpBox_error.setTitle(_translate("spider_monitor", "Fehler:"))
        self.grpBox_neu.setTitle(_translate("spider_monitor", "Neu:"))
        self.grpBox_update.setTitle(_translate("spider_monitor", "updatet:"))
        self.lblZeit.setText(_translate("spider_monitor", "Zeit:"))
        self.Btn_break.setText(_translate("spider_monitor", "Abbruch"))
        self.Btn_back.setText(_translate("spider_monitor", "zurück"))
        self.Btn_start.setText(_translate("spider_monitor", "start"))
