# Form implementation generated from reading ui file 'e:\Python\Python_WORK\Datei_Info_Creator\gui\uic_imports\url_input_dialog.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_dialog_seturl(object):
    def setupUi(self, dialog_seturl):
        dialog_seturl.setObjectName("dialog_seturl")
        dialog_seturl.resize(451, 78)
        dialog_seturl.setSizeGripEnabled(True)
        dialog_seturl.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(dialog_seturl)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.lnEdit_website_url = QtWidgets.QLineEdit(parent=dialog_seturl)
        self.lnEdit_website_url.setMinimumSize(QtCore.QSize(400, 25))
        self.lnEdit_website_url.setStyleSheet("background-color: #FFFDD5;")
        self.lnEdit_website_url.setObjectName("lnEdit_website_url")
        self.horizontalLayout_2.addWidget(self.lnEdit_website_url)
        self.Btn_link_copy = QtWidgets.QPushButton(parent=dialog_seturl)
        self.Btn_link_copy.setMinimumSize(QtCore.QSize(25, 25))
        self.Btn_link_copy.setMaximumSize(QtCore.QSize(25, 25))
        self.Btn_link_copy.setStyleSheet("background-color: #FFFDD5;")
        self.Btn_link_copy.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/labels/_labels/copy_clip.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.Btn_link_copy.setIcon(icon)
        self.Btn_link_copy.setFlat(True)
        self.Btn_link_copy.setObjectName("Btn_link_copy")
        self.horizontalLayout_2.addWidget(self.Btn_link_copy)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lblstatus = QtWidgets.QLabel(parent=dialog_seturl)
        self.lblstatus.setObjectName("lblstatus")
        self.horizontalLayout.addWidget(self.lblstatus)
        self.lbl_status = QtWidgets.QLabel(parent=dialog_seturl)
        self.lbl_status.setMinimumSize(QtCore.QSize(60, 0))
        self.lbl_status.setStyleSheet("background-color: #FFFDD5;")
        self.lbl_status.setFrameShape(QtWidgets.QFrame.Shape.Box)
        self.lbl_status.setText("")
        self.lbl_status.setObjectName("lbl_status")
        self.horizontalLayout.addWidget(self.lbl_status)
        self.lblstatus_icon = QtWidgets.QLabel(parent=dialog_seturl)
        self.lblstatus_icon.setMinimumSize(QtCore.QSize(20, 20))
        self.lblstatus_icon.setText("")
        self.lblstatus_icon.setObjectName("lblstatus_icon")
        self.horizontalLayout.addWidget(self.lblstatus_icon)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=dialog_seturl)
        self.buttonBox.setMinimumSize(QtCore.QSize(0, 25))
        self.buttonBox.setStyleSheet("QPushButton { \n"
"    color: rgb(0, 0, 127);\n"
"    selection-background-color: rgb(255, 85, 0);\n"
"    background-color: rgb(198, 178, 255);\n"
"    border-style: outset;\n"
"    border-width: 2px;\n"
"    font: 14pt \"MS Shell Dlg 2\";\n"
"    border-radius: 5px;\n"
"    border-color: beige;\n"
"}                   \n"
"QPushButton:enabled{\n"
"    background-color: rgb(198, 178, 255);\n"
"}                           \n"
"QPushButton:pressed{ \n"
"    background: red;\n"
"}                            \n"
"QPushButton:disabled{                             \n"
"    background-color: gray;                \n"
"}\n"
"QPushButton:hover{\n"
"    background-color: rgb(255, 85, 255);\n"
"}   ")
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout.addWidget(self.buttonBox)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.lnEdit_website_url.raise_()

        self.retranslateUi(dialog_seturl)
        self.buttonBox.accepted.connect(dialog_seturl.accept) # type: ignore
        self.buttonBox.rejected.connect(dialog_seturl.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(dialog_seturl)

    def retranslateUi(self, dialog_seturl):
        _translate = QtCore.QCoreApplication.translate
        dialog_seturl.setWindowTitle(_translate("dialog_seturl", "Dialog"))
        self.lnEdit_website_url.setPlaceholderText(_translate("dialog_seturl", "gebe eine URL ein"))
        self.Btn_link_copy.setToolTip(_translate("dialog_seturl", "kopiert den Link in die Ziwschenablage"))
        self.lblstatus.setText(_translate("dialog_seturl", "Status:"))
